{
  "hash": "1c0a5f8f0ef31cbc789c7aa9bf250c34",
  "result": {
    "markdown": "---\ntitle: \"Some practice\"\nformat: \n  html:\n    self-contained: true\n    code-line-numbers: true\n  pdf: \n    documentclass: article\ncustom_title_page: false\nfilters:\n  - lightbox\nlightbox: auto\n---\n\n---\nsubtitle: \"Let's practice some usefull commands\"\ndate: 2023-02-27\n\nauthor:\n  - name: Javier Silva-Valencia\n    orcid: 0000-0002-5982-2821\n    email: javier.silva@unmsm.edu.pe\n    affiliations:\n      - name: Instituut Voor Tropische Geneeskunde. Antwerp-Belgium\n\nlanguage: \n  title-block-author-single: \"Writer\"\n  \nabstract: Today we had an introduction to how to create subsets by row, subset by colls, appending (joining up-down), merging (joining left-righ).\n---\n\n\n------------------------------------------------------------------------\n\n------------------------------------------------------------------------\n\n### Exercise 1\n\nLet's practice dividing and joining data.\n\n#### Import CSV\n\nImporting the CSV database under the name of Q1_B, with \",\" as separator, and with \".\" as decimal:\n\n\n::: {.cell hash='Data-Analysis-Wk1_cache/html/unnamed-chunk-1_30d3bb5fb63ce58427a3720c9445766b'}\n\n```{.r .cell-code .numberLines}\nQ1_B <- read.csv(\"C:/Users/pined/OneDrive - Universidad Nacional Mayor de San Marcos/Javier 2022/Belgica/AC2_DataAnalysis_ThWk/Material/Q1_B.csv\", sep=\",\", dec= \".\")\n```\n:::\n\n\n#### Create a subset by row\n\nChecking the identification variable of this dataset (FSN)\n\n\n::: {.cell hash='Data-Analysis-Wk1_cache/html/unnamed-chunk-2_60b2057e1f4dcdfb9a256a20b8658084'}\n\n```{.r .cell-code .numberLines}\nsummary(Q1_B$FSN)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  45001   48527   52032   52110   55671   59606 \n```\n:::\n:::\n\n\n::: callout-tip\nThe median is 52032\n:::\n\nLet's divide the data in two parts taking as cut point the half of the rows (The median of FSN)\n\n\n::: {.cell hash='Data-Analysis-Wk1_cache/html/unnamed-chunk-3_dc9408c2161a0729eed702106b50e721'}\n\n```{.r .cell-code .numberLines}\ntop <- subset(Q1_B, subset= FSN < 52032)\nbottom <- subset(Q1_B, subset= FSN >= 52032)\n```\n:::\n\n\nSeeing the structure of the original dataset and the new subsets\n\n\n::: {.cell hash='Data-Analysis-Wk1_cache/html/unnamed-chunk-4_02421215550f4a8dc493a4d3a1431f7c'}\n\n```{.r .cell-code .numberLines}\nstr(Q1_B)     #Original dataset\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t13377 obs. of  40 variables:\n $ ID                 : int  1 2 3 4 5 6 7 8 9 10 ...\n $ FSN                : num  45001 45002 45003 45004 45005 ...\n $ Neem_Tree          : num  0 0 0 0 0 0 0 0 0 0 ...\n $ Neem_Tree_Distance : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Neem_Tree_Size     : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Neem_Tree_Age      : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Neem_Tree_Usage    : chr  \"\" \"\" \"\" \"\" ...\n $ Neem_Tree_Use_Other: chr  \"\" \"\" \"\" \"\" ...\n $ Bamboo_Tree        : num  1 1 1 1 1 1 1 1 1 1 ...\n $ Bamboo_Tree_Dist   : num  3 10 16 17 5 4 15 3 1 10 ...\n $ Banana_Tree        : num  0 0 0 0 0 0 0 1 1 0 ...\n $ Banana_Tree_Dist   : num  -1 -1 -1 -1 -1 -1 -1 5 1 -1 ...\n $ Rice_Field         : num  1 1 1 1 1 1 1 1 1 1 ...\n $ Rice_Field_Dist    : num  4 12 16 13 4 13 10 10 7 12 ...\n $ Perm_Water_Body    : num  0 0 0 0 0 0 0 0 0 0 ...\n $ Perm_Wat_Body_Dist : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Wat_Body_Mid_Point : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ No_Mosquito_Net    : num  0 2 1 0 0 0 0 0 1 0 ...\n $ Sprayed_2010       : num  86 86 86 86 86 86 86 86 86 86 ...\n $ Sprayed_2009       : num  86 86 86 86 86 86 86 86 86 86 ...\n $ Floor_Material     : num  153 153 153 153 153 153 153 153 155 153 ...\n $ Other_Floor_Mat    : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Is_Floor_Damp      : num  1 1 1 1 1 1 1 1 0 1 ...\n $ Roof_Material      : num  161 159 158 156 156 156 156 158 158 156 ...\n $ Other_Roof_Material: num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Wall_Material      : num  164 164 164 162 163 163 162 164 164 162 ...\n $ Other_Wall_Material: num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Windows_in_Room    : num  1 1 1 0 0 0 0 1 1 0 ...\n $ Granaries_in_HH    : num  1 1 1 0 1 1 0 1 1 0 ...\n $ Source_Drink_Water : num  167 167 92 92 92 92 92 92 92 92 ...\n $ Other_Src_Drink_Wat: num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Toilet_Facility    : num  177 177 177 177 177 177 177 177 177 177 ...\n $ Other_Toilet_Fac   : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Cooking_Fuel       : num  180 180 180 180 180 180 180 180 180 180 ...\n $ Other_Cooking_Fuel : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Source_Light       : num  182 182 182 182 182 182 182 182 182 182 ...\n $ Other_Source_Light : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Electricity_in_HH  : num  0 0 0 0 0 0 0 0 0 0 ...\n $ No_Of_Rooms        : num  2 2 3 1 2 3 2 1 3 1 ...\n $ No_Sleeping_Rooms  : num  2 2 2 1 2 2 2 1 1 1 ...\n```\n:::\n\n```{.r .cell-code .numberLines}\nstr(top)      #Subset top of the data\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t6688 obs. of  40 variables:\n $ ID                 : int  1 2 3 4 5 6 7 8 9 10 ...\n $ FSN                : num  45001 45002 45003 45004 45005 ...\n $ Neem_Tree          : num  0 0 0 0 0 0 0 0 0 0 ...\n $ Neem_Tree_Distance : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Neem_Tree_Size     : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Neem_Tree_Age      : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Neem_Tree_Usage    : chr  \"\" \"\" \"\" \"\" ...\n $ Neem_Tree_Use_Other: chr  \"\" \"\" \"\" \"\" ...\n $ Bamboo_Tree        : num  1 1 1 1 1 1 1 1 1 1 ...\n $ Bamboo_Tree_Dist   : num  3 10 16 17 5 4 15 3 1 10 ...\n $ Banana_Tree        : num  0 0 0 0 0 0 0 1 1 0 ...\n $ Banana_Tree_Dist   : num  -1 -1 -1 -1 -1 -1 -1 5 1 -1 ...\n $ Rice_Field         : num  1 1 1 1 1 1 1 1 1 1 ...\n $ Rice_Field_Dist    : num  4 12 16 13 4 13 10 10 7 12 ...\n $ Perm_Water_Body    : num  0 0 0 0 0 0 0 0 0 0 ...\n $ Perm_Wat_Body_Dist : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Wat_Body_Mid_Point : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ No_Mosquito_Net    : num  0 2 1 0 0 0 0 0 1 0 ...\n $ Sprayed_2010       : num  86 86 86 86 86 86 86 86 86 86 ...\n $ Sprayed_2009       : num  86 86 86 86 86 86 86 86 86 86 ...\n $ Floor_Material     : num  153 153 153 153 153 153 153 153 155 153 ...\n $ Other_Floor_Mat    : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Is_Floor_Damp      : num  1 1 1 1 1 1 1 1 0 1 ...\n $ Roof_Material      : num  161 159 158 156 156 156 156 158 158 156 ...\n $ Other_Roof_Material: num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Wall_Material      : num  164 164 164 162 163 163 162 164 164 162 ...\n $ Other_Wall_Material: num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Windows_in_Room    : num  1 1 1 0 0 0 0 1 1 0 ...\n $ Granaries_in_HH    : num  1 1 1 0 1 1 0 1 1 0 ...\n $ Source_Drink_Water : num  167 167 92 92 92 92 92 92 92 92 ...\n $ Other_Src_Drink_Wat: num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Toilet_Facility    : num  177 177 177 177 177 177 177 177 177 177 ...\n $ Other_Toilet_Fac   : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Cooking_Fuel       : num  180 180 180 180 180 180 180 180 180 180 ...\n $ Other_Cooking_Fuel : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Source_Light       : num  182 182 182 182 182 182 182 182 182 182 ...\n $ Other_Source_Light : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Electricity_in_HH  : num  0 0 0 0 0 0 0 0 0 0 ...\n $ No_Of_Rooms        : num  2 2 3 1 2 3 2 1 3 1 ...\n $ No_Sleeping_Rooms  : num  2 2 2 1 2 2 2 1 1 1 ...\n```\n:::\n\n```{.r .cell-code .numberLines}\nstr(bottom)   #Subset bottom of the data\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t6689 obs. of  40 variables:\n $ ID                 : int  6689 6690 6691 6692 6693 6694 6695 6696 6697 6698 ...\n $ FSN                : num  52032 52033 52034 52035 52036 ...\n $ Neem_Tree          : num  1 1 1 1 1 1 1 1 1 0 ...\n $ Neem_Tree_Distance : num  12 30 38 38 12 16 20 25 45 -1 ...\n $ Neem_Tree_Size     : num  2 2 2 2 2 2 2 2 2 -1 ...\n $ Neem_Tree_Age      : num  2 2 2 2 2 2 2 2 2 -1 ...\n $ Neem_Tree_Usage    : chr  \"188_\" \"188_\" \"188_\" \"188_\" ...\n $ Neem_Tree_Use_Other: chr  \"\" \"\" \"\" \"\" ...\n $ Bamboo_Tree        : num  0 0 0 0 1 1 0 0 0 1 ...\n $ Bamboo_Tree_Dist   : num  -1 -1 -1 -1 5 15 -1 -1 -1 18 ...\n $ Banana_Tree        : num  1 1 0 0 1 1 1 1 1 1 ...\n $ Banana_Tree_Dist   : num  1 20 -1 -1 1 16 5 2 1 1 ...\n $ Rice_Field         : num  0 1 1 1 1 1 1 1 1 1 ...\n $ Rice_Field_Dist    : num  -1 1 1 1 10 15 18 12 1 2 ...\n $ Perm_Water_Body    : num  0 0 0 0 1 1 1 1 1 1 ...\n $ Perm_Wat_Body_Dist : num  -1 -1 -1 -1 2 1 8 12 26 17 ...\n $ Wat_Body_Mid_Point : num  -1 -1 -1 -1 1 1 1 1 1 1 ...\n $ No_Mosquito_Net    : num  1 1 1 0 1 4 4 5 1 0 ...\n $ Sprayed_2010       : num  86 86 86 86 86 86 86 86 86 86 ...\n $ Sprayed_2009       : num  86 86 86 86 86 86 86 86 86 86 ...\n $ Floor_Material     : num  153 153 153 153 153 153 155 155 153 153 ...\n $ Other_Floor_Mat    : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Is_Floor_Damp      : num  1 1 1 1 1 1 0 0 1 0 ...\n $ Roof_Material      : num  161 156 156 156 54 158 158 158 161 158 ...\n $ Other_Roof_Material: num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Wall_Material      : num  164 162 162 162 164 165 165 165 164 165 ...\n $ Other_Wall_Material: num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Windows_in_Room    : num  0 0 0 0 1 1 1 1 1 1 ...\n $ Granaries_in_HH    : num  1 1 1 1 1 1 1 1 1 1 ...\n $ Source_Drink_Water : num  92 167 167 92 167 167 167 167 167 167 ...\n $ Other_Src_Drink_Wat: num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Toilet_Facility    : num  177 177 177 177 177 174 174 174 177 174 ...\n $ Other_Toilet_Fac   : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Cooking_Fuel       : num  180 180 180 180 180 180 180 180 180 180 ...\n $ Other_Cooking_Fuel : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Source_Light       : num  182 182 182 182 182 182 182 182 182 182 ...\n $ Other_Source_Light : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Electricity_in_HH  : num  0 0 0 0 0 1 1 1 0 0 ...\n $ No_Of_Rooms        : num  2 2 1 1 3 4 5 4 3 1 ...\n $ No_Sleeping_Rooms  : num  1 2 1 1 2 3 4 3 1 1 ...\n```\n:::\n:::\n\n\n::: callout-tip\nIn Q1_B we have 13377 obs\n\nIf we sum the observations in the subsets:\n\nTop + bottom: 6688 + 6689 =13377\n\nSo, it is ok\n:::\n\n#### Joining (Append)\nLet's join the two subsets (top and bottom)\n\n\n::: {.cell hash='Data-Analysis-Wk1_cache/html/unnamed-chunk-5_d5b5a5482accb5dba88995cd1d593c57'}\n\n```{.r .cell-code .numberLines}\nmerged_top_bottom  <-  rbind(top,bottom)  #To merge\nstr(merged_top_bottom)                    #To see the result\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t13377 obs. of  40 variables:\n $ ID                 : int  1 2 3 4 5 6 7 8 9 10 ...\n $ FSN                : num  45001 45002 45003 45004 45005 ...\n $ Neem_Tree          : num  0 0 0 0 0 0 0 0 0 0 ...\n $ Neem_Tree_Distance : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Neem_Tree_Size     : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Neem_Tree_Age      : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Neem_Tree_Usage    : chr  \"\" \"\" \"\" \"\" ...\n $ Neem_Tree_Use_Other: chr  \"\" \"\" \"\" \"\" ...\n $ Bamboo_Tree        : num  1 1 1 1 1 1 1 1 1 1 ...\n $ Bamboo_Tree_Dist   : num  3 10 16 17 5 4 15 3 1 10 ...\n $ Banana_Tree        : num  0 0 0 0 0 0 0 1 1 0 ...\n $ Banana_Tree_Dist   : num  -1 -1 -1 -1 -1 -1 -1 5 1 -1 ...\n $ Rice_Field         : num  1 1 1 1 1 1 1 1 1 1 ...\n $ Rice_Field_Dist    : num  4 12 16 13 4 13 10 10 7 12 ...\n $ Perm_Water_Body    : num  0 0 0 0 0 0 0 0 0 0 ...\n $ Perm_Wat_Body_Dist : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Wat_Body_Mid_Point : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ No_Mosquito_Net    : num  0 2 1 0 0 0 0 0 1 0 ...\n $ Sprayed_2010       : num  86 86 86 86 86 86 86 86 86 86 ...\n $ Sprayed_2009       : num  86 86 86 86 86 86 86 86 86 86 ...\n $ Floor_Material     : num  153 153 153 153 153 153 153 153 155 153 ...\n $ Other_Floor_Mat    : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Is_Floor_Damp      : num  1 1 1 1 1 1 1 1 0 1 ...\n $ Roof_Material      : num  161 159 158 156 156 156 156 158 158 156 ...\n $ Other_Roof_Material: num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Wall_Material      : num  164 164 164 162 163 163 162 164 164 162 ...\n $ Other_Wall_Material: num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Windows_in_Room    : num  1 1 1 0 0 0 0 1 1 0 ...\n $ Granaries_in_HH    : num  1 1 1 0 1 1 0 1 1 0 ...\n $ Source_Drink_Water : num  167 167 92 92 92 92 92 92 92 92 ...\n $ Other_Src_Drink_Wat: num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Toilet_Facility    : num  177 177 177 177 177 177 177 177 177 177 ...\n $ Other_Toilet_Fac   : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Cooking_Fuel       : num  180 180 180 180 180 180 180 180 180 180 ...\n $ Other_Cooking_Fuel : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Source_Light       : num  182 182 182 182 182 182 182 182 182 182 ...\n $ Other_Source_Light : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Electricity_in_HH  : num  0 0 0 0 0 0 0 0 0 0 ...\n $ No_Of_Rooms        : num  2 2 3 1 2 3 2 1 3 1 ...\n $ No_Sleeping_Rooms  : num  2 2 2 1 2 2 2 1 1 1 ...\n```\n:::\n:::\n\n\n::: callout-tip\nThere are 13377 obs \n\nIt is the same of the original, So it is ok\n:::\n\n#### Create a subset by coll\n\nSeeing the names of the collums (name of the variables)\n\n\n::: {.cell hash='Data-Analysis-Wk1_cache/html/unnamed-chunk-6_b44157c1261e2fc24a598497364397fc'}\n\n```{.r .cell-code .numberLines}\nnames(Q1_B)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] \"ID\"                  \"FSN\"                 \"Neem_Tree\"          \n [4] \"Neem_Tree_Distance\"  \"Neem_Tree_Size\"      \"Neem_Tree_Age\"      \n [7] \"Neem_Tree_Usage\"     \"Neem_Tree_Use_Other\" \"Bamboo_Tree\"        \n[10] \"Bamboo_Tree_Dist\"    \"Banana_Tree\"         \"Banana_Tree_Dist\"   \n[13] \"Rice_Field\"          \"Rice_Field_Dist\"     \"Perm_Water_Body\"    \n[16] \"Perm_Wat_Body_Dist\"  \"Wat_Body_Mid_Point\"  \"No_Mosquito_Net\"    \n[19] \"Sprayed_2010\"        \"Sprayed_2009\"        \"Floor_Material\"     \n[22] \"Other_Floor_Mat\"     \"Is_Floor_Damp\"       \"Roof_Material\"      \n[25] \"Other_Roof_Material\" \"Wall_Material\"       \"Other_Wall_Material\"\n[28] \"Windows_in_Room\"     \"Granaries_in_HH\"     \"Source_Drink_Water\" \n[31] \"Other_Src_Drink_Wat\" \"Toilet_Facility\"     \"Other_Toilet_Fac\"   \n[34] \"Cooking_Fuel\"        \"Other_Cooking_Fuel\"  \"Source_Light\"       \n[37] \"Other_Source_Light\"  \"Electricity_in_HH\"   \"No_Of_Rooms\"        \n[40] \"No_Sleeping_Rooms\"  \n```\n:::\n:::\n\n\nLet's divide the data in two parts taking as cut point the half of the columns\n\nWe have to be careful to keep an identification variable in each subset (in this case is FSN)\n\n\n::: {.cell hash='Data-Analysis-Wk1_cache/html/unnamed-chunk-7_649fd7f9ccdc592a7300ae4c21fb09ad'}\n\n```{.r .cell-code .numberLines}\nLeft <- subset(Q1_B, select=c(\"ID\", \"FSN\", \"Neem_Tree\", \"Neem_Tree_Distance\", \"Neem_Tree_Size\", \"Neem_Tree_Age\", \"Neem_Tree_Usage\", \"Neem_Tree_Use_Other\", \"Bamboo_Tree\", \"Bamboo_Tree_Dist\", \"Banana_Tree\", \"Banana_Tree_Dist\", \"Rice_Field\", \"Rice_Field_Dist\", \"Perm_Water_Body\", \"Perm_Wat_Body_Dist\",  \"Wat_Body_Mid_Point\", \"No_Mosquito_Net\", \"Sprayed_2010\", \"Sprayed_2009\", \"Floor_Material\"))\nstr(Left)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t13377 obs. of  21 variables:\n $ ID                 : int  1 2 3 4 5 6 7 8 9 10 ...\n $ FSN                : num  45001 45002 45003 45004 45005 ...\n $ Neem_Tree          : num  0 0 0 0 0 0 0 0 0 0 ...\n $ Neem_Tree_Distance : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Neem_Tree_Size     : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Neem_Tree_Age      : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Neem_Tree_Usage    : chr  \"\" \"\" \"\" \"\" ...\n $ Neem_Tree_Use_Other: chr  \"\" \"\" \"\" \"\" ...\n $ Bamboo_Tree        : num  1 1 1 1 1 1 1 1 1 1 ...\n $ Bamboo_Tree_Dist   : num  3 10 16 17 5 4 15 3 1 10 ...\n $ Banana_Tree        : num  0 0 0 0 0 0 0 1 1 0 ...\n $ Banana_Tree_Dist   : num  -1 -1 -1 -1 -1 -1 -1 5 1 -1 ...\n $ Rice_Field         : num  1 1 1 1 1 1 1 1 1 1 ...\n $ Rice_Field_Dist    : num  4 12 16 13 4 13 10 10 7 12 ...\n $ Perm_Water_Body    : num  0 0 0 0 0 0 0 0 0 0 ...\n $ Perm_Wat_Body_Dist : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Wat_Body_Mid_Point : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ No_Mosquito_Net    : num  0 2 1 0 0 0 0 0 1 0 ...\n $ Sprayed_2010       : num  86 86 86 86 86 86 86 86 86 86 ...\n $ Sprayed_2009       : num  86 86 86 86 86 86 86 86 86 86 ...\n $ Floor_Material     : num  153 153 153 153 153 153 153 153 155 153 ...\n```\n:::\n:::\n\n::: {.cell hash='Data-Analysis-Wk1_cache/html/unnamed-chunk-8_4aa7c50e920c7deaf7cefd074b6cc686'}\n\n```{.r .cell-code .numberLines}\nRigth <- subset(Q1_B, select=c(\"FSN\", \"Other_Floor_Mat\", \"Is_Floor_Damp\", \"Roof_Material\", \"Other_Roof_Material\", \"Wall_Material\", \"Other_Wall_Material\", \"Windows_in_Room\", \"Granaries_in_HH\", \"Source_Drink_Water\", \"Other_Src_Drink_Wat\", \"Toilet_Facility\", \"Other_Toilet_Fac\", \"Cooking_Fuel\", \"Other_Cooking_Fuel\", \"Source_Light\", \"Other_Source_Light\", \"Electricity_in_HH\", \"No_Of_Rooms\", \"No_Sleeping_Rooms\"))\n\n#Or select the opposite (With a \"-\" in front of the c):\n#Rigth <- subset(Q1_B, select=-c(\"ID\", \"Neem_Tree\", \"Neem_Tree_Distance\", \"Neem_Tree_Size\", \"Neem_Tree_Age\", \"Neem_Tree_Usage\", \"Neem_Tree_Use_Other\", \"Bamboo_Tree\", \"Bamboo_Tree_Dist\", \"Banana_Tree\", \"Banana_Tree_Dist\", \"Rice_Field\", \"Rice_Field_Dist\", \"Perm_Water_Body\", \"Perm_Wat_Body_Dist\",  \"Wat_Body_Mid_Point\", \"No_Mosquito_Net\", \"Sprayed_2010\", \"Sprayed_2009\", \"Floor_Material\"))\n\nstr(Rigth)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t13377 obs. of  20 variables:\n $ FSN                : num  45001 45002 45003 45004 45005 ...\n $ Other_Floor_Mat    : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Is_Floor_Damp      : num  1 1 1 1 1 1 1 1 0 1 ...\n $ Roof_Material      : num  161 159 158 156 156 156 156 158 158 156 ...\n $ Other_Roof_Material: num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Wall_Material      : num  164 164 164 162 163 163 162 164 164 162 ...\n $ Other_Wall_Material: num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Windows_in_Room    : num  1 1 1 0 0 0 0 1 1 0 ...\n $ Granaries_in_HH    : num  1 1 1 0 1 1 0 1 1 0 ...\n $ Source_Drink_Water : num  167 167 92 92 92 92 92 92 92 92 ...\n $ Other_Src_Drink_Wat: num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Toilet_Facility    : num  177 177 177 177 177 177 177 177 177 177 ...\n $ Other_Toilet_Fac   : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Cooking_Fuel       : num  180 180 180 180 180 180 180 180 180 180 ...\n $ Other_Cooking_Fuel : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Source_Light       : num  182 182 182 182 182 182 182 182 182 182 ...\n $ Other_Source_Light : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Electricity_in_HH  : num  0 0 0 0 0 0 0 0 0 0 ...\n $ No_Of_Rooms        : num  2 2 3 1 2 3 2 1 3 1 ...\n $ No_Sleeping_Rooms  : num  2 2 2 1 2 2 2 1 1 1 ...\n```\n:::\n:::\n\n\n#### Joining (Merge)\n\nLet's join the two subsets (left and right) according to the FSN \n\n\n::: {.cell hash='Data-Analysis-Wk1_cache/html/unnamed-chunk-9_65ec523728d2ba524ba3dbcd1a1909dc'}\n\n```{.r .cell-code .numberLines}\nmerged_left_right  <-  merge(Left, Rigth, all=TRUE, by = \"FSN\")\nstr(merged_left_right)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t13377 obs. of  40 variables:\n $ FSN                : num  45001 45002 45003 45004 45005 ...\n $ ID                 : int  1 2 3 4 5 6 7 8 9 10 ...\n $ Neem_Tree          : num  0 0 0 0 0 0 0 0 0 0 ...\n $ Neem_Tree_Distance : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Neem_Tree_Size     : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Neem_Tree_Age      : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Neem_Tree_Usage    : chr  \"\" \"\" \"\" \"\" ...\n $ Neem_Tree_Use_Other: chr  \"\" \"\" \"\" \"\" ...\n $ Bamboo_Tree        : num  1 1 1 1 1 1 1 1 1 1 ...\n $ Bamboo_Tree_Dist   : num  3 10 16 17 5 4 15 3 1 10 ...\n $ Banana_Tree        : num  0 0 0 0 0 0 0 1 1 0 ...\n $ Banana_Tree_Dist   : num  -1 -1 -1 -1 -1 -1 -1 5 1 -1 ...\n $ Rice_Field         : num  1 1 1 1 1 1 1 1 1 1 ...\n $ Rice_Field_Dist    : num  4 12 16 13 4 13 10 10 7 12 ...\n $ Perm_Water_Body    : num  0 0 0 0 0 0 0 0 0 0 ...\n $ Perm_Wat_Body_Dist : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Wat_Body_Mid_Point : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ No_Mosquito_Net    : num  0 2 1 0 0 0 0 0 1 0 ...\n $ Sprayed_2010       : num  86 86 86 86 86 86 86 86 86 86 ...\n $ Sprayed_2009       : num  86 86 86 86 86 86 86 86 86 86 ...\n $ Floor_Material     : num  153 153 153 153 153 153 153 153 155 153 ...\n $ Other_Floor_Mat    : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Is_Floor_Damp      : num  1 1 1 1 1 1 1 1 0 1 ...\n $ Roof_Material      : num  161 159 158 156 156 156 156 158 158 156 ...\n $ Other_Roof_Material: num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Wall_Material      : num  164 164 164 162 163 163 162 164 164 162 ...\n $ Other_Wall_Material: num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Windows_in_Room    : num  1 1 1 0 0 0 0 1 1 0 ...\n $ Granaries_in_HH    : num  1 1 1 0 1 1 0 1 1 0 ...\n $ Source_Drink_Water : num  167 167 92 92 92 92 92 92 92 92 ...\n $ Other_Src_Drink_Wat: num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Toilet_Facility    : num  177 177 177 177 177 177 177 177 177 177 ...\n $ Other_Toilet_Fac   : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Cooking_Fuel       : num  180 180 180 180 180 180 180 180 180 180 ...\n $ Other_Cooking_Fuel : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Source_Light       : num  182 182 182 182 182 182 182 182 182 182 ...\n $ Other_Source_Light : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Electricity_in_HH  : num  0 0 0 0 0 0 0 0 0 0 ...\n $ No_Of_Rooms        : num  2 2 3 1 2 3 2 1 3 1 ...\n $ No_Sleeping_Rooms  : num  2 2 2 1 2 2 2 1 1 1 ...\n```\n:::\n:::\n\n\n\n\n### Exercise 2\n\nLet's practice renaming variables and replacing values\n\n\n::: {.cell hash='Data-Analysis-Wk1_cache/html/unnamed-chunk-10_5909075d9122df8702bc7992065f3911'}\n\n```{.r .cell-code .numberLines}\nQ1_B_1 <- read.csv(\"C:/Users/pined/OneDrive - Universidad Nacional Mayor de San Marcos/Javier 2022/Belgica/AC2_DataAnalysis_ThWk/Material/Q1_B_1.csv\", sep=\",\", dec= \".\")\n```\n:::\n\n::: {.cell hash='Data-Analysis-Wk1_cache/html/unnamed-chunk-11_f5d65eea5892bf666231e39336e91d8e'}\n\n```{.r .cell-code .numberLines}\nstr(Q1_B_1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t9029 obs. of  6 variables:\n $ FSN              : int  45001 45001 45002 45003 45004 45006 45009 45021 45021 45024 ...\n $ Animal_Name      : chr  \"Goats\" \"Poultry (chickens, ducks, pigeon)\" \"Buffaloes\" \"Cows/Oxen\" ...\n $ Animal_Count     : int  3 1 1 1 2 2 7 3 1 3 ...\n $ Animal_Distance  : int  5 0 4 3 5 0 0 15 5 15 ...\n $ Keep_Inside_House: int  1 1 0 1 1 1 1 0 1 1 ...\n $ Days_Inside_House: int  120 365 -1 210 180 360 360 -1 150 90 ...\n```\n:::\n\n```{.r .cell-code .numberLines}\nhead(Q1_B_1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    FSN                       Animal_Name Animal_Count Animal_Distance\n1 45001                             Goats            3               5\n2 45001 Poultry (chickens, ducks, pigeon)            1               0\n3 45002                         Buffaloes            1               4\n4 45003                         Cows/Oxen            1               3\n5 45004                             Goats            2               5\n6 45006                         Cows/Oxen            2               0\n  Keep_Inside_House Days_Inside_House\n1                 1               120\n2                 1               365\n3                 0                -1\n4                 1               210\n5                 1               180\n6                 1               360\n```\n:::\n:::\n\n\n::: callout-tip\nWe observe: \n\n- There are 9029 obs \n\n- The animal name is quite large sometimes \n\n- The variable names are quite large\n:::\n\n\n#### Renaming variables\n\nRenaming variables labels: In collumns 2-5 to \"anim\", \"count\", \"dist\", \"indor\", \"daysin\"\n\n\n::: {.cell hash='Data-Analysis-Wk1_cache/html/unnamed-chunk-12_3321b1ad839eb9be635ffbf9b3b9dc33'}\n\n```{.r .cell-code .numberLines}\nnames(Q1_B_1)[c(2,3,4,5,6)] <- c(\"anim\", \"count\", \"dist\", \"indor\", \"daysin\")\nstr(Q1_B_1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t9029 obs. of  6 variables:\n $ FSN   : int  45001 45001 45002 45003 45004 45006 45009 45021 45021 45024 ...\n $ anim  : chr  \"Goats\" \"Poultry (chickens, ducks, pigeon)\" \"Buffaloes\" \"Cows/Oxen\" ...\n $ count : int  3 1 1 1 2 2 7 3 1 3 ...\n $ dist  : int  5 0 4 3 5 0 0 15 5 15 ...\n $ indor : int  1 1 0 1 1 1 1 0 1 1 ...\n $ daysin: int  120 365 -1 210 180 360 360 -1 150 90 ...\n```\n:::\n\n```{.r .cell-code .numberLines}\n#View(Q1_B_1)\n```\n:::\n\n::: {.cell hash='Data-Analysis-Wk1_cache/html/unnamed-chunk-13_208d8c050f8f46a9e11ac0e7d51ce89b'}\n\n```{.r .cell-code .numberLines}\ntable(Q1_B_1$count)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  -1    0    1    2    3    4    5    6    7    8    9   10   11   12   14   15 \n   8   10 4104 3288  885  451  135   83   23   15    2    9    1    3    1    1 \n  16   20   30   35   50   60 \n   3    1    1    1    2    2 \n```\n:::\n\n```{.r .cell-code .numberLines}\ntable(Q1_B_1$dist)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  -1    0    1    2    3    4    5    6    7    8    9   10   11   12   13   14 \n  24 3307  492  774  618  255  953  238  173  217   11  578   10   87    7    9 \n  15   16   17   18   19   20   22   23   24   25   26   29   30   32   35   38 \n 231    9    3   28    4  149   12    2    1   59    1    2   70    1   40    2 \n  40   43   45   49   50   55   58   60   68   69   70   75   80   90   95  100 \n  31    1   13    1  133   10    1   29    2    3   17   14    4    1    1  163 \n 105  110  120  150  180  200  210  250  300  400  500  600 1000 \n   3    7    3   60    2   77    2    4   19    9   40    9    3 \n```\n:::\n\n```{.r .cell-code .numberLines}\ntable(Q1_B_1$indor)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n   0    1   89 \n4816 4200   13 \n```\n:::\n\n```{.r .cell-code .numberLines}\ntable(Q1_B_1$daysin)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  -1    0    1    3    5    7    8   10   12   15   18   20   30   35   40   45 \n4823    1    2    1    4    2    2    8    1    1    1    3   48    2    2    7 \n  50   60   65   70   80   90  100  110  120  122  130  150  160  165  175  180 \n   2   84    1    1    5  192   23    2  273    1    2   74   13    5    2  466 \n 190  200  210  215  220  230  240  245  250  260  265  270  280  300  310  340 \n   1   57   11    1    1    4   82    1   10    7    3    3   33   36    1    1 \n 350  355  356  360  365 \n   1    1    1   21 2699 \n```\n:::\n:::\n\n\n#### Replacing values in observations\n\n\n::: {.cell hash='Data-Analysis-Wk1_cache/html/unnamed-chunk-14_b6c6cbf73d31a16265f039f1a68b44c7'}\n\n```{.r .cell-code .numberLines}\ntable(Q1_B_1$anim)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n                        Buffaloes                         Cows/Oxen \n                             1592                              3055 \n                             Dogs                             Goats \n                               38                              3816 \n                            Other                              Pigs \n                                3                                20 \nPoultry (chickens, ducks, pigeon) \n                              505 \n```\n:::\n\n```{.r .cell-code .numberLines}\nQ1_B_1$anim[Q1_B_1$anim ==\"Buffaloes\"] <- \"Buff\"\nQ1_B_1$anim[Q1_B_1$anim ==\"Goats\"] <- \"Goat\"\n\n#But if we want to keep the 4 (x) first characters in a all rows\nQ1_B_1$anim <- substr(Q1_B_1$anim, 0, 3)\ntable(Q1_B_1$anim)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n Buf  Cow  Dog  Goa  Oth  Pig  Pou \n1592 3055   38 3816    3   20  505 \n```\n:::\n\n```{.r .cell-code .numberLines}\nstr(Q1_B_1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t9029 obs. of  6 variables:\n $ FSN   : int  45001 45001 45002 45003 45004 45006 45009 45021 45021 45024 ...\n $ anim  : chr  \"Goa\" \"Pou\" \"Buf\" \"Cow\" ...\n $ count : int  3 1 1 1 2 2 7 3 1 3 ...\n $ dist  : int  5 0 4 3 5 0 0 15 5 15 ...\n $ indor : int  1 1 0 1 1 1 1 0 1 1 ...\n $ daysin: int  120 365 -1 210 180 360 360 -1 150 90 ...\n```\n:::\n:::\n\n\n\nWe are going to save this data because we are going to use it later\n\n::: {.cell hash='Data-Analysis-Wk1_cache/html/unnamed-chunk-15_1ab5253378faa012329b869d4655f7cf'}\n\n```{.r .cell-code .numberLines}\nsaveRDS(Q1_B_1, \"Q1_B_1.RDS\")\n```\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}