{
  "hash": "ae006604f953f21917d712d85286ccd5",
  "result": {
    "markdown": "---\ntitle: \"Data Analysis Wk1\"\nformat: \n  html:\n    self-contained: true\n    code-line-numbers: true\n  pdf: \n    documentclass: article\ncustom_title_page: false\nfilters:\n  - lightbox\nlightbox: auto\n---\n\n---\nsubtitle: \"Data Analysis Week - Session 1\"\ndate: 2023-02-27\n\nauthor:\n  - name: Javier Silva-Valencia\n    orcid: 0000-0002-5982-2821\n    email: javier.silva@unmsm.edu.pe\n    affiliations:\n      - name: Instituut Voor Tropische Geneeskunde. Antwerp-Belgium\n\nlanguage: \n  title-block-author-single: \"Writer\"\n  \nabstract: Today we had an introduction to how to create subsets by row, subset by colls, appending (joining up-down), merging (joining left-righ), and how to reshape the database. Animals dataset is only the datasets that have animals in the dataset.\n---\n\n\n------------------------------------------------------------------------\n\n------------------------------------------------------------------------\n\n### Exercise 1\n\n\n#### Import CSV\n\nSet working directory: We are not going to do it\n\nImporting the CSV database under the name of Q1_B, with \",\" as separator, and with \".\" as decimal:\n\n\n::: {.cell hash='The-case_cache/html/unnamed-chunk-1_c3b2802481dcf4da6a93e79d0a0f1d53'}\n\n```{.r .cell-code .numberLines}\nQ1_B <- read.csv(\"C:/Users/pined/OneDrive - Universidad Nacional Mayor de San Marcos/Javier 2022/Belgica/AC2_DataAnalysis_ThWk/Material/Q1_B.csv\", sep=\",\", dec= \".\")\n```\n:::\n\n\n#### Subset by row\n\nSeeing FSN\n\n\n::: {.cell hash='The-case_cache/html/unnamed-chunk-2_0aef59b6fa8b3236523b64b71dcd0604'}\n\n```{.r .cell-code .numberLines}\nsummary(Q1_B$FSN)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  45001   48527   52032   52110   55671   59606 \n```\n:::\n:::\n\n\n::: callout-tip\nThe median is 52032\n:::\n\nCreating subset\n\n\n::: {.cell hash='The-case_cache/html/unnamed-chunk-3_7c0bf4d17718f7779e31858be6dbaf0c'}\n\n```{.r .cell-code .numberLines}\ntop <- subset(Q1_B, subset= FSN < 52032)\nbottom <- subset(Q1_B, subset= FSN >= 52032)\n```\n:::\n\n\nSeeing the structure in all sets\n\n\n::: {.cell hash='The-case_cache/html/unnamed-chunk-4_be0377d9d68ea5092e720ae0ab547a47'}\n\n```{.r .cell-code .numberLines}\nstr(Q1_B)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t13377 obs. of  40 variables:\n $ ID                 : int  1 2 3 4 5 6 7 8 9 10 ...\n $ FSN                : num  45001 45002 45003 45004 45005 ...\n $ Neem_Tree          : num  0 0 0 0 0 0 0 0 0 0 ...\n $ Neem_Tree_Distance : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Neem_Tree_Size     : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Neem_Tree_Age      : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Neem_Tree_Usage    : chr  \"\" \"\" \"\" \"\" ...\n $ Neem_Tree_Use_Other: chr  \"\" \"\" \"\" \"\" ...\n $ Bamboo_Tree        : num  1 1 1 1 1 1 1 1 1 1 ...\n $ Bamboo_Tree_Dist   : num  3 10 16 17 5 4 15 3 1 10 ...\n $ Banana_Tree        : num  0 0 0 0 0 0 0 1 1 0 ...\n $ Banana_Tree_Dist   : num  -1 -1 -1 -1 -1 -1 -1 5 1 -1 ...\n $ Rice_Field         : num  1 1 1 1 1 1 1 1 1 1 ...\n $ Rice_Field_Dist    : num  4 12 16 13 4 13 10 10 7 12 ...\n $ Perm_Water_Body    : num  0 0 0 0 0 0 0 0 0 0 ...\n $ Perm_Wat_Body_Dist : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Wat_Body_Mid_Point : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ No_Mosquito_Net    : num  0 2 1 0 0 0 0 0 1 0 ...\n $ Sprayed_2010       : num  86 86 86 86 86 86 86 86 86 86 ...\n $ Sprayed_2009       : num  86 86 86 86 86 86 86 86 86 86 ...\n $ Floor_Material     : num  153 153 153 153 153 153 153 153 155 153 ...\n $ Other_Floor_Mat    : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Is_Floor_Damp      : num  1 1 1 1 1 1 1 1 0 1 ...\n $ Roof_Material      : num  161 159 158 156 156 156 156 158 158 156 ...\n $ Other_Roof_Material: num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Wall_Material      : num  164 164 164 162 163 163 162 164 164 162 ...\n $ Other_Wall_Material: num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Windows_in_Room    : num  1 1 1 0 0 0 0 1 1 0 ...\n $ Granaries_in_HH    : num  1 1 1 0 1 1 0 1 1 0 ...\n $ Source_Drink_Water : num  167 167 92 92 92 92 92 92 92 92 ...\n $ Other_Src_Drink_Wat: num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Toilet_Facility    : num  177 177 177 177 177 177 177 177 177 177 ...\n $ Other_Toilet_Fac   : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Cooking_Fuel       : num  180 180 180 180 180 180 180 180 180 180 ...\n $ Other_Cooking_Fuel : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Source_Light       : num  182 182 182 182 182 182 182 182 182 182 ...\n $ Other_Source_Light : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Electricity_in_HH  : num  0 0 0 0 0 0 0 0 0 0 ...\n $ No_Of_Rooms        : num  2 2 3 1 2 3 2 1 3 1 ...\n $ No_Sleeping_Rooms  : num  2 2 2 1 2 2 2 1 1 1 ...\n```\n:::\n\n```{.r .cell-code .numberLines}\nstr(top)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t6688 obs. of  40 variables:\n $ ID                 : int  1 2 3 4 5 6 7 8 9 10 ...\n $ FSN                : num  45001 45002 45003 45004 45005 ...\n $ Neem_Tree          : num  0 0 0 0 0 0 0 0 0 0 ...\n $ Neem_Tree_Distance : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Neem_Tree_Size     : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Neem_Tree_Age      : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Neem_Tree_Usage    : chr  \"\" \"\" \"\" \"\" ...\n $ Neem_Tree_Use_Other: chr  \"\" \"\" \"\" \"\" ...\n $ Bamboo_Tree        : num  1 1 1 1 1 1 1 1 1 1 ...\n $ Bamboo_Tree_Dist   : num  3 10 16 17 5 4 15 3 1 10 ...\n $ Banana_Tree        : num  0 0 0 0 0 0 0 1 1 0 ...\n $ Banana_Tree_Dist   : num  -1 -1 -1 -1 -1 -1 -1 5 1 -1 ...\n $ Rice_Field         : num  1 1 1 1 1 1 1 1 1 1 ...\n $ Rice_Field_Dist    : num  4 12 16 13 4 13 10 10 7 12 ...\n $ Perm_Water_Body    : num  0 0 0 0 0 0 0 0 0 0 ...\n $ Perm_Wat_Body_Dist : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Wat_Body_Mid_Point : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ No_Mosquito_Net    : num  0 2 1 0 0 0 0 0 1 0 ...\n $ Sprayed_2010       : num  86 86 86 86 86 86 86 86 86 86 ...\n $ Sprayed_2009       : num  86 86 86 86 86 86 86 86 86 86 ...\n $ Floor_Material     : num  153 153 153 153 153 153 153 153 155 153 ...\n $ Other_Floor_Mat    : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Is_Floor_Damp      : num  1 1 1 1 1 1 1 1 0 1 ...\n $ Roof_Material      : num  161 159 158 156 156 156 156 158 158 156 ...\n $ Other_Roof_Material: num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Wall_Material      : num  164 164 164 162 163 163 162 164 164 162 ...\n $ Other_Wall_Material: num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Windows_in_Room    : num  1 1 1 0 0 0 0 1 1 0 ...\n $ Granaries_in_HH    : num  1 1 1 0 1 1 0 1 1 0 ...\n $ Source_Drink_Water : num  167 167 92 92 92 92 92 92 92 92 ...\n $ Other_Src_Drink_Wat: num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Toilet_Facility    : num  177 177 177 177 177 177 177 177 177 177 ...\n $ Other_Toilet_Fac   : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Cooking_Fuel       : num  180 180 180 180 180 180 180 180 180 180 ...\n $ Other_Cooking_Fuel : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Source_Light       : num  182 182 182 182 182 182 182 182 182 182 ...\n $ Other_Source_Light : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Electricity_in_HH  : num  0 0 0 0 0 0 0 0 0 0 ...\n $ No_Of_Rooms        : num  2 2 3 1 2 3 2 1 3 1 ...\n $ No_Sleeping_Rooms  : num  2 2 2 1 2 2 2 1 1 1 ...\n```\n:::\n\n```{.r .cell-code .numberLines}\nstr(bottom)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t6689 obs. of  40 variables:\n $ ID                 : int  6689 6690 6691 6692 6693 6694 6695 6696 6697 6698 ...\n $ FSN                : num  52032 52033 52034 52035 52036 ...\n $ Neem_Tree          : num  1 1 1 1 1 1 1 1 1 0 ...\n $ Neem_Tree_Distance : num  12 30 38 38 12 16 20 25 45 -1 ...\n $ Neem_Tree_Size     : num  2 2 2 2 2 2 2 2 2 -1 ...\n $ Neem_Tree_Age      : num  2 2 2 2 2 2 2 2 2 -1 ...\n $ Neem_Tree_Usage    : chr  \"188_\" \"188_\" \"188_\" \"188_\" ...\n $ Neem_Tree_Use_Other: chr  \"\" \"\" \"\" \"\" ...\n $ Bamboo_Tree        : num  0 0 0 0 1 1 0 0 0 1 ...\n $ Bamboo_Tree_Dist   : num  -1 -1 -1 -1 5 15 -1 -1 -1 18 ...\n $ Banana_Tree        : num  1 1 0 0 1 1 1 1 1 1 ...\n $ Banana_Tree_Dist   : num  1 20 -1 -1 1 16 5 2 1 1 ...\n $ Rice_Field         : num  0 1 1 1 1 1 1 1 1 1 ...\n $ Rice_Field_Dist    : num  -1 1 1 1 10 15 18 12 1 2 ...\n $ Perm_Water_Body    : num  0 0 0 0 1 1 1 1 1 1 ...\n $ Perm_Wat_Body_Dist : num  -1 -1 -1 -1 2 1 8 12 26 17 ...\n $ Wat_Body_Mid_Point : num  -1 -1 -1 -1 1 1 1 1 1 1 ...\n $ No_Mosquito_Net    : num  1 1 1 0 1 4 4 5 1 0 ...\n $ Sprayed_2010       : num  86 86 86 86 86 86 86 86 86 86 ...\n $ Sprayed_2009       : num  86 86 86 86 86 86 86 86 86 86 ...\n $ Floor_Material     : num  153 153 153 153 153 153 155 155 153 153 ...\n $ Other_Floor_Mat    : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Is_Floor_Damp      : num  1 1 1 1 1 1 0 0 1 0 ...\n $ Roof_Material      : num  161 156 156 156 54 158 158 158 161 158 ...\n $ Other_Roof_Material: num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Wall_Material      : num  164 162 162 162 164 165 165 165 164 165 ...\n $ Other_Wall_Material: num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Windows_in_Room    : num  0 0 0 0 1 1 1 1 1 1 ...\n $ Granaries_in_HH    : num  1 1 1 1 1 1 1 1 1 1 ...\n $ Source_Drink_Water : num  92 167 167 92 167 167 167 167 167 167 ...\n $ Other_Src_Drink_Wat: num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Toilet_Facility    : num  177 177 177 177 177 174 174 174 177 174 ...\n $ Other_Toilet_Fac   : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Cooking_Fuel       : num  180 180 180 180 180 180 180 180 180 180 ...\n $ Other_Cooking_Fuel : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Source_Light       : num  182 182 182 182 182 182 182 182 182 182 ...\n $ Other_Source_Light : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Electricity_in_HH  : num  0 0 0 0 0 1 1 1 0 0 ...\n $ No_Of_Rooms        : num  2 2 1 1 3 4 5 4 3 1 ...\n $ No_Sleeping_Rooms  : num  1 2 1 1 2 3 4 3 1 1 ...\n```\n:::\n:::\n\n\n::: callout-tip\nIn Q1_B we have 13377 obs\n\nTop + bottom: 6688 + 6689 =13377\n\nSo, it is ok\n:::\n\n#### Joining (Append)\n\n\n::: {.cell hash='The-case_cache/html/unnamed-chunk-5_5f6cffe148472209802a87380a97d434'}\n\n```{.r .cell-code .numberLines}\nmerged_top_bottom  <-  rbind(top,bottom)\nstr(merged_top_bottom)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t13377 obs. of  40 variables:\n $ ID                 : int  1 2 3 4 5 6 7 8 9 10 ...\n $ FSN                : num  45001 45002 45003 45004 45005 ...\n $ Neem_Tree          : num  0 0 0 0 0 0 0 0 0 0 ...\n $ Neem_Tree_Distance : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Neem_Tree_Size     : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Neem_Tree_Age      : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Neem_Tree_Usage    : chr  \"\" \"\" \"\" \"\" ...\n $ Neem_Tree_Use_Other: chr  \"\" \"\" \"\" \"\" ...\n $ Bamboo_Tree        : num  1 1 1 1 1 1 1 1 1 1 ...\n $ Bamboo_Tree_Dist   : num  3 10 16 17 5 4 15 3 1 10 ...\n $ Banana_Tree        : num  0 0 0 0 0 0 0 1 1 0 ...\n $ Banana_Tree_Dist   : num  -1 -1 -1 -1 -1 -1 -1 5 1 -1 ...\n $ Rice_Field         : num  1 1 1 1 1 1 1 1 1 1 ...\n $ Rice_Field_Dist    : num  4 12 16 13 4 13 10 10 7 12 ...\n $ Perm_Water_Body    : num  0 0 0 0 0 0 0 0 0 0 ...\n $ Perm_Wat_Body_Dist : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Wat_Body_Mid_Point : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ No_Mosquito_Net    : num  0 2 1 0 0 0 0 0 1 0 ...\n $ Sprayed_2010       : num  86 86 86 86 86 86 86 86 86 86 ...\n $ Sprayed_2009       : num  86 86 86 86 86 86 86 86 86 86 ...\n $ Floor_Material     : num  153 153 153 153 153 153 153 153 155 153 ...\n $ Other_Floor_Mat    : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Is_Floor_Damp      : num  1 1 1 1 1 1 1 1 0 1 ...\n $ Roof_Material      : num  161 159 158 156 156 156 156 158 158 156 ...\n $ Other_Roof_Material: num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Wall_Material      : num  164 164 164 162 163 163 162 164 164 162 ...\n $ Other_Wall_Material: num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Windows_in_Room    : num  1 1 1 0 0 0 0 1 1 0 ...\n $ Granaries_in_HH    : num  1 1 1 0 1 1 0 1 1 0 ...\n $ Source_Drink_Water : num  167 167 92 92 92 92 92 92 92 92 ...\n $ Other_Src_Drink_Wat: num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Toilet_Facility    : num  177 177 177 177 177 177 177 177 177 177 ...\n $ Other_Toilet_Fac   : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Cooking_Fuel       : num  180 180 180 180 180 180 180 180 180 180 ...\n $ Other_Cooking_Fuel : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Source_Light       : num  182 182 182 182 182 182 182 182 182 182 ...\n $ Other_Source_Light : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Electricity_in_HH  : num  0 0 0 0 0 0 0 0 0 0 ...\n $ No_Of_Rooms        : num  2 2 3 1 2 3 2 1 3 1 ...\n $ No_Sleeping_Rooms  : num  2 2 2 1 2 2 2 1 1 1 ...\n```\n:::\n:::\n\n\n::: callout-tip\nThere are 13377 obs\n\nSo, it is ok\n:::\n\n#### Subset by colls\n\nSeeing the names of the variable\n\n\n::: {.cell hash='The-case_cache/html/unnamed-chunk-6_f3c9a5f192d1d8f4742bb7757e3c63e0'}\n\n```{.r .cell-code .numberLines}\nnames(Q1_B)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] \"ID\"                  \"FSN\"                 \"Neem_Tree\"          \n [4] \"Neem_Tree_Distance\"  \"Neem_Tree_Size\"      \"Neem_Tree_Age\"      \n [7] \"Neem_Tree_Usage\"     \"Neem_Tree_Use_Other\" \"Bamboo_Tree\"        \n[10] \"Bamboo_Tree_Dist\"    \"Banana_Tree\"         \"Banana_Tree_Dist\"   \n[13] \"Rice_Field\"          \"Rice_Field_Dist\"     \"Perm_Water_Body\"    \n[16] \"Perm_Wat_Body_Dist\"  \"Wat_Body_Mid_Point\"  \"No_Mosquito_Net\"    \n[19] \"Sprayed_2010\"        \"Sprayed_2009\"        \"Floor_Material\"     \n[22] \"Other_Floor_Mat\"     \"Is_Floor_Damp\"       \"Roof_Material\"      \n[25] \"Other_Roof_Material\" \"Wall_Material\"       \"Other_Wall_Material\"\n[28] \"Windows_in_Room\"     \"Granaries_in_HH\"     \"Source_Drink_Water\" \n[31] \"Other_Src_Drink_Wat\" \"Toilet_Facility\"     \"Other_Toilet_Fac\"   \n[34] \"Cooking_Fuel\"        \"Other_Cooking_Fuel\"  \"Source_Light\"       \n[37] \"Other_Source_Light\"  \"Electricity_in_HH\"   \"No_Of_Rooms\"        \n[40] \"No_Sleeping_Rooms\"  \n```\n:::\n:::\n\n::: {.cell hash='The-case_cache/html/unnamed-chunk-7_67ae3de216aea8f3e5e9fb6d4823ced6'}\n\n```{.r .cell-code .numberLines}\nLeft <- subset(Q1_B, select=c(\"ID\", \"FSN\", \"Neem_Tree\", \"Neem_Tree_Distance\", \"Neem_Tree_Size\", \"Neem_Tree_Age\", \"Neem_Tree_Usage\", \"Neem_Tree_Use_Other\", \"Bamboo_Tree\", \"Bamboo_Tree_Dist\", \"Banana_Tree\", \"Banana_Tree_Dist\", \"Rice_Field\", \"Rice_Field_Dist\", \"Perm_Water_Body\", \"Perm_Wat_Body_Dist\",  \"Wat_Body_Mid_Point\", \"No_Mosquito_Net\", \"Sprayed_2010\", \"Sprayed_2009\", \"Floor_Material\"))\nstr(Left)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t13377 obs. of  21 variables:\n $ ID                 : int  1 2 3 4 5 6 7 8 9 10 ...\n $ FSN                : num  45001 45002 45003 45004 45005 ...\n $ Neem_Tree          : num  0 0 0 0 0 0 0 0 0 0 ...\n $ Neem_Tree_Distance : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Neem_Tree_Size     : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Neem_Tree_Age      : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Neem_Tree_Usage    : chr  \"\" \"\" \"\" \"\" ...\n $ Neem_Tree_Use_Other: chr  \"\" \"\" \"\" \"\" ...\n $ Bamboo_Tree        : num  1 1 1 1 1 1 1 1 1 1 ...\n $ Bamboo_Tree_Dist   : num  3 10 16 17 5 4 15 3 1 10 ...\n $ Banana_Tree        : num  0 0 0 0 0 0 0 1 1 0 ...\n $ Banana_Tree_Dist   : num  -1 -1 -1 -1 -1 -1 -1 5 1 -1 ...\n $ Rice_Field         : num  1 1 1 1 1 1 1 1 1 1 ...\n $ Rice_Field_Dist    : num  4 12 16 13 4 13 10 10 7 12 ...\n $ Perm_Water_Body    : num  0 0 0 0 0 0 0 0 0 0 ...\n $ Perm_Wat_Body_Dist : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Wat_Body_Mid_Point : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ No_Mosquito_Net    : num  0 2 1 0 0 0 0 0 1 0 ...\n $ Sprayed_2010       : num  86 86 86 86 86 86 86 86 86 86 ...\n $ Sprayed_2009       : num  86 86 86 86 86 86 86 86 86 86 ...\n $ Floor_Material     : num  153 153 153 153 153 153 153 153 155 153 ...\n```\n:::\n:::\n\n::: {.cell hash='The-case_cache/html/unnamed-chunk-8_84fba6871a11581078c6bff3515db877'}\n\n```{.r .cell-code .numberLines}\nRigth <- subset(Q1_B, select=c(\"FSN\", \"Other_Floor_Mat\", \"Is_Floor_Damp\", \"Roof_Material\", \"Other_Roof_Material\", \"Wall_Material\", \"Other_Wall_Material\", \"Windows_in_Room\", \"Granaries_in_HH\", \"Source_Drink_Water\", \"Other_Src_Drink_Wat\", \"Toilet_Facility\", \"Other_Toilet_Fac\", \"Cooking_Fuel\", \"Other_Cooking_Fuel\", \"Source_Light\", \"Other_Source_Light\", \"Electricity_in_HH\", \"No_Of_Rooms\", \"No_Sleeping_Rooms\"))\n\n#Or select the opposite (With a \"-\" in front of the c):\n#Rigth <- subset(Q1_B, select=-c(\"ID\", \"Neem_Tree\", \"Neem_Tree_Distance\", \"Neem_Tree_Size\", \"Neem_Tree_Age\", \"Neem_Tree_Usage\", \"Neem_Tree_Use_Other\", \"Bamboo_Tree\", \"Bamboo_Tree_Dist\", \"Banana_Tree\", \"Banana_Tree_Dist\", \"Rice_Field\", \"Rice_Field_Dist\", \"Perm_Water_Body\", \"Perm_Wat_Body_Dist\",  \"Wat_Body_Mid_Point\", \"No_Mosquito_Net\", \"Sprayed_2010\", \"Sprayed_2009\", \"Floor_Material\"))\n\nstr(Rigth)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t13377 obs. of  20 variables:\n $ FSN                : num  45001 45002 45003 45004 45005 ...\n $ Other_Floor_Mat    : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Is_Floor_Damp      : num  1 1 1 1 1 1 1 1 0 1 ...\n $ Roof_Material      : num  161 159 158 156 156 156 156 158 158 156 ...\n $ Other_Roof_Material: num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Wall_Material      : num  164 164 164 162 163 163 162 164 164 162 ...\n $ Other_Wall_Material: num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Windows_in_Room    : num  1 1 1 0 0 0 0 1 1 0 ...\n $ Granaries_in_HH    : num  1 1 1 0 1 1 0 1 1 0 ...\n $ Source_Drink_Water : num  167 167 92 92 92 92 92 92 92 92 ...\n $ Other_Src_Drink_Wat: num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Toilet_Facility    : num  177 177 177 177 177 177 177 177 177 177 ...\n $ Other_Toilet_Fac   : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Cooking_Fuel       : num  180 180 180 180 180 180 180 180 180 180 ...\n $ Other_Cooking_Fuel : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Source_Light       : num  182 182 182 182 182 182 182 182 182 182 ...\n $ Other_Source_Light : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Electricity_in_HH  : num  0 0 0 0 0 0 0 0 0 0 ...\n $ No_Of_Rooms        : num  2 2 3 1 2 3 2 1 3 1 ...\n $ No_Sleeping_Rooms  : num  2 2 2 1 2 2 2 1 1 1 ...\n```\n:::\n:::\n\n\n#### Joining (Merge)\n\nJoin database by ID\n\n\n::: {.cell hash='The-case_cache/html/unnamed-chunk-9_838cf18593ff98c7572e73eec57e86b2'}\n\n```{.r .cell-code .numberLines}\nmerged_left_right  <-  merge(Left, Rigth, all=TRUE, by = \"FSN\")\nstr(merged_left_right)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t13377 obs. of  40 variables:\n $ FSN                : num  45001 45002 45003 45004 45005 ...\n $ ID                 : int  1 2 3 4 5 6 7 8 9 10 ...\n $ Neem_Tree          : num  0 0 0 0 0 0 0 0 0 0 ...\n $ Neem_Tree_Distance : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Neem_Tree_Size     : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Neem_Tree_Age      : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Neem_Tree_Usage    : chr  \"\" \"\" \"\" \"\" ...\n $ Neem_Tree_Use_Other: chr  \"\" \"\" \"\" \"\" ...\n $ Bamboo_Tree        : num  1 1 1 1 1 1 1 1 1 1 ...\n $ Bamboo_Tree_Dist   : num  3 10 16 17 5 4 15 3 1 10 ...\n $ Banana_Tree        : num  0 0 0 0 0 0 0 1 1 0 ...\n $ Banana_Tree_Dist   : num  -1 -1 -1 -1 -1 -1 -1 5 1 -1 ...\n $ Rice_Field         : num  1 1 1 1 1 1 1 1 1 1 ...\n $ Rice_Field_Dist    : num  4 12 16 13 4 13 10 10 7 12 ...\n $ Perm_Water_Body    : num  0 0 0 0 0 0 0 0 0 0 ...\n $ Perm_Wat_Body_Dist : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Wat_Body_Mid_Point : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ No_Mosquito_Net    : num  0 2 1 0 0 0 0 0 1 0 ...\n $ Sprayed_2010       : num  86 86 86 86 86 86 86 86 86 86 ...\n $ Sprayed_2009       : num  86 86 86 86 86 86 86 86 86 86 ...\n $ Floor_Material     : num  153 153 153 153 153 153 153 153 155 153 ...\n $ Other_Floor_Mat    : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Is_Floor_Damp      : num  1 1 1 1 1 1 1 1 0 1 ...\n $ Roof_Material      : num  161 159 158 156 156 156 156 158 158 156 ...\n $ Other_Roof_Material: num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Wall_Material      : num  164 164 164 162 163 163 162 164 164 162 ...\n $ Other_Wall_Material: num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Windows_in_Room    : num  1 1 1 0 0 0 0 1 1 0 ...\n $ Granaries_in_HH    : num  1 1 1 0 1 1 0 1 1 0 ...\n $ Source_Drink_Water : num  167 167 92 92 92 92 92 92 92 92 ...\n $ Other_Src_Drink_Wat: num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Toilet_Facility    : num  177 177 177 177 177 177 177 177 177 177 ...\n $ Other_Toilet_Fac   : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Cooking_Fuel       : num  180 180 180 180 180 180 180 180 180 180 ...\n $ Other_Cooking_Fuel : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Source_Light       : num  182 182 182 182 182 182 182 182 182 182 ...\n $ Other_Source_Light : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Electricity_in_HH  : num  0 0 0 0 0 0 0 0 0 0 ...\n $ No_Of_Rooms        : num  2 2 3 1 2 3 2 1 3 1 ...\n $ No_Sleeping_Rooms  : num  2 2 2 1 2 2 2 1 1 1 ...\n```\n:::\n:::\n\n\n### Exercise 2\n\n\n::: {.cell hash='The-case_cache/html/unnamed-chunk-10_4089f4f8f504116baa13b997f107178b'}\n\n```{.r .cell-code .numberLines}\nQ1_B_1 <- read.csv(\"C:/Users/pined/OneDrive - Universidad Nacional Mayor de San Marcos/Javier 2022/Belgica/AC2_DataAnalysis_ThWk/Material/Q1_B_1.csv\", sep=\",\", dec= \".\")\n```\n:::\n\n::: {.cell hash='The-case_cache/html/unnamed-chunk-11_9ee8d59b3ec22f0fa41409ef40a830d7'}\n\n```{.r .cell-code .numberLines}\nstr(Q1_B_1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t9029 obs. of  6 variables:\n $ FSN              : int  45001 45001 45002 45003 45004 45006 45009 45021 45021 45024 ...\n $ Animal_Name      : chr  \"Goats\" \"Poultry (chickens, ducks, pigeon)\" \"Buffaloes\" \"Cows/Oxen\" ...\n $ Animal_Count     : int  3 1 1 1 2 2 7 3 1 3 ...\n $ Animal_Distance  : int  5 0 4 3 5 0 0 15 5 15 ...\n $ Keep_Inside_House: int  1 1 0 1 1 1 1 0 1 1 ...\n $ Days_Inside_House: int  120 365 -1 210 180 360 360 -1 150 90 ...\n```\n:::\n\n```{.r .cell-code .numberLines}\nhead(Q1_B_1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    FSN                       Animal_Name Animal_Count Animal_Distance\n1 45001                             Goats            3               5\n2 45001 Poultry (chickens, ducks, pigeon)            1               0\n3 45002                         Buffaloes            1               4\n4 45003                         Cows/Oxen            1               3\n5 45004                             Goats            2               5\n6 45006                         Cows/Oxen            2               0\n  Keep_Inside_House Days_Inside_House\n1                 1               120\n2                 1               365\n3                 0                -1\n4                 1               210\n5                 1               180\n6                 1               360\n```\n:::\n:::\n\n\n::: callout-tip\nWe observe: - There are 9029 obs - There are duplicates in FSN - The animal name is quite large sometimes - The variable names are quite large\n:::\n\n#### Renaming variables\n\nRenaming variables labels: In collumns 2-5 to \"anim\", \"count\", \"dist\", \"indor\", \"daysin\"\n\n\n::: {.cell hash='The-case_cache/html/unnamed-chunk-12_248258eb5de9cb2084e370a22978213c'}\n\n```{.r .cell-code .numberLines}\nnames(Q1_B_1)[c(2,3,4,5,6)] <- c(\"anim\", \"count\", \"dist\", \"indor\", \"daysin\")\nstr(Q1_B_1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t9029 obs. of  6 variables:\n $ FSN   : int  45001 45001 45002 45003 45004 45006 45009 45021 45021 45024 ...\n $ anim  : chr  \"Goats\" \"Poultry (chickens, ducks, pigeon)\" \"Buffaloes\" \"Cows/Oxen\" ...\n $ count : int  3 1 1 1 2 2 7 3 1 3 ...\n $ dist  : int  5 0 4 3 5 0 0 15 5 15 ...\n $ indor : int  1 1 0 1 1 1 1 0 1 1 ...\n $ daysin: int  120 365 -1 210 180 360 360 -1 150 90 ...\n```\n:::\n\n```{.r .cell-code .numberLines}\n#View(Q1_B_1)\n```\n:::\n\n::: {.cell hash='The-case_cache/html/unnamed-chunk-13_353867e3625efd8ecd238ee1d27bf486'}\n\n```{.r .cell-code .numberLines}\ntable(Q1_B_1$count)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  -1    0    1    2    3    4    5    6    7    8    9   10   11   12   14   15 \n   8   10 4104 3288  885  451  135   83   23   15    2    9    1    3    1    1 \n  16   20   30   35   50   60 \n   3    1    1    1    2    2 \n```\n:::\n\n```{.r .cell-code .numberLines}\ntable(Q1_B_1$dist)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  -1    0    1    2    3    4    5    6    7    8    9   10   11   12   13   14 \n  24 3307  492  774  618  255  953  238  173  217   11  578   10   87    7    9 \n  15   16   17   18   19   20   22   23   24   25   26   29   30   32   35   38 \n 231    9    3   28    4  149   12    2    1   59    1    2   70    1   40    2 \n  40   43   45   49   50   55   58   60   68   69   70   75   80   90   95  100 \n  31    1   13    1  133   10    1   29    2    3   17   14    4    1    1  163 \n 105  110  120  150  180  200  210  250  300  400  500  600 1000 \n   3    7    3   60    2   77    2    4   19    9   40    9    3 \n```\n:::\n\n```{.r .cell-code .numberLines}\ntable(Q1_B_1$indor)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n   0    1   89 \n4816 4200   13 \n```\n:::\n\n```{.r .cell-code .numberLines}\ntable(Q1_B_1$daysin)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  -1    0    1    3    5    7    8   10   12   15   18   20   30   35   40   45 \n4823    1    2    1    4    2    2    8    1    1    1    3   48    2    2    7 \n  50   60   65   70   80   90  100  110  120  122  130  150  160  165  175  180 \n   2   84    1    1    5  192   23    2  273    1    2   74   13    5    2  466 \n 190  200  210  215  220  230  240  245  250  260  265  270  280  300  310  340 \n   1   57   11    1    1    4   82    1   10    7    3    3   33   36    1    1 \n 350  355  356  360  365 \n   1    1    1   21 2699 \n```\n:::\n:::\n\n\n#### Replacing values in observations\n\n\n::: {.cell hash='The-case_cache/html/unnamed-chunk-14_4e2dc136e4074c96713c0310e8bf79df'}\n\n```{.r .cell-code .numberLines}\ntable(Q1_B_1$anim)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n                        Buffaloes                         Cows/Oxen \n                             1592                              3055 \n                             Dogs                             Goats \n                               38                              3816 \n                            Other                              Pigs \n                                3                                20 \nPoultry (chickens, ducks, pigeon) \n                              505 \n```\n:::\n\n```{.r .cell-code .numberLines}\nQ1_B_1$anim[Q1_B_1$anim ==\"Buffaloes\"] <- \"Buff\"\nQ1_B_1$anim[Q1_B_1$anim ==\"Goats\"] <- \"Goat\"\n\n#But if we want to keep the 4 (x) first characters in a all rows\nQ1_B_1$anim <- substr(Q1_B_1$anim, 0, 3)\ntable(Q1_B_1$anim)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n Buf  Cow  Dog  Goa  Oth  Pig  Pou \n1592 3055   38 3816    3   20  505 \n```\n:::\n\n```{.r .cell-code .numberLines}\nstr(Q1_B_1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t9029 obs. of  6 variables:\n $ FSN   : int  45001 45001 45002 45003 45004 45006 45009 45021 45021 45024 ...\n $ anim  : chr  \"Goa\" \"Pou\" \"Buf\" \"Cow\" ...\n $ count : int  3 1 1 1 2 2 7 3 1 3 ...\n $ dist  : int  5 0 4 3 5 0 0 15 5 15 ...\n $ indor : int  1 1 0 1 1 1 1 0 1 1 ...\n $ daysin: int  120 365 -1 210 180 360 360 -1 150 90 ...\n```\n:::\n:::\n\n\n#### Long to Wide\n\nWe need one line for each household\n\nSo, we will use reshape command to say: Reshape the database taking in to account that i want to make the database wider, having just one line for household (FSN) and replicating the variables count, dist, indor, daysin for every animal that the household had.\n\n\n::: {.cell hash='The-case_cache/html/unnamed-chunk-15_00645a790394f9fdebffc1db00eda2c5'}\n\n```{.r .cell-code .numberLines}\nanimals <- reshape(Q1_B_1,direction = \"wide\", timevar =\"anim\", idvar =\"FSN\", v.names = c(\"count\",\"dist\",\"indor\", \"daysin\"), sep = \"_\")\nstr(animals)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t7147 obs. of  29 variables:\n $ FSN       : int  45001 45002 45003 45004 45006 45009 45021 45024 45025 45027 ...\n $ count_Goa : int  3 NA NA 2 NA 7 1 3 3 NA ...\n $ dist_Goa  : int  5 NA NA 5 NA 0 5 15 0 NA ...\n $ indor_Goa : int  1 NA NA 1 NA 1 1 1 1 NA ...\n $ daysin_Goa: int  120 NA NA 180 NA 360 150 90 90 NA ...\n $ count_Pou : int  1 NA NA NA NA NA NA NA NA 2 ...\n $ dist_Pou  : int  0 NA NA NA NA NA NA NA NA 0 ...\n $ indor_Pou : int  1 NA NA NA NA NA NA NA NA 1 ...\n $ daysin_Pou: int  365 NA NA NA NA NA NA NA NA 360 ...\n $ count_Buf : int  NA 1 NA NA NA NA NA NA NA NA ...\n $ dist_Buf  : int  NA 4 NA NA NA NA NA NA NA NA ...\n $ indor_Buf : int  NA 0 NA NA NA NA NA NA NA NA ...\n $ daysin_Buf: int  NA -1 NA NA NA NA NA NA NA NA ...\n $ count_Cow : int  NA NA 1 NA 2 NA 3 NA NA NA ...\n $ dist_Cow  : int  NA NA 3 NA 0 NA 15 NA NA NA ...\n $ indor_Cow : int  NA NA 1 NA 1 NA 0 NA NA NA ...\n $ daysin_Cow: int  NA NA 210 NA 360 NA -1 NA NA NA ...\n $ count_Pig : int  NA NA NA NA NA NA NA NA NA NA ...\n $ dist_Pig  : int  NA NA NA NA NA NA NA NA NA NA ...\n $ indor_Pig : int  NA NA NA NA NA NA NA NA NA NA ...\n $ daysin_Pig: int  NA NA NA NA NA NA NA NA NA NA ...\n $ count_Dog : int  NA NA NA NA NA NA NA NA NA NA ...\n $ dist_Dog  : int  NA NA NA NA NA NA NA NA NA NA ...\n $ indor_Dog : int  NA NA NA NA NA NA NA NA NA NA ...\n $ daysin_Dog: int  NA NA NA NA NA NA NA NA NA NA ...\n $ count_Oth : int  NA NA NA NA NA NA NA NA NA NA ...\n $ dist_Oth  : int  NA NA NA NA NA NA NA NA NA NA ...\n $ indor_Oth : int  NA NA NA NA NA NA NA NA NA NA ...\n $ daysin_Oth: int  NA NA NA NA NA NA NA NA NA NA ...\n - attr(*, \"reshapeWide\")=List of 5\n  ..$ v.names: chr [1:4] \"count\" \"dist\" \"indor\" \"daysin\"\n  ..$ timevar: chr \"anim\"\n  ..$ idvar  : chr \"FSN\"\n  ..$ times  : chr [1:7] \"Goa\" \"Pou\" \"Buf\" \"Cow\" ...\n  ..$ varying: chr [1:4, 1:7] \"count_Goa\" \"dist_Goa\" \"indor_Goa\" \"daysin_Goa\" ...\n```\n:::\n\n```{.r .cell-code .numberLines}\nclass(animals)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"data.frame\"\n```\n:::\n\n```{.r .cell-code .numberLines}\n#View(animals)\n```\n:::\n\n\n::: callout-tip\nWe observe: - That now we have less observations (7147)(before was 9029 obs) (so some houses had more than one animal) - There are a lot of NA (households than doesn't have that animal) - There are also some -1\n:::\n\n#### Replacing NA\n\nWe want to replace the NA and the -1 to Zero in all columns\n\n\n::: {.cell hash='The-case_cache/html/unnamed-chunk-16_3f1ed60e118df338dfefaa2fc633b526'}\n\n```{.r .cell-code .numberLines}\nnames(animals)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] \"FSN\"        \"count_Goa\"  \"dist_Goa\"   \"indor_Goa\"  \"daysin_Goa\"\n [6] \"count_Pou\"  \"dist_Pou\"   \"indor_Pou\"  \"daysin_Pou\" \"count_Buf\" \n[11] \"dist_Buf\"   \"indor_Buf\"  \"daysin_Buf\" \"count_Cow\"  \"dist_Cow\"  \n[16] \"indor_Cow\"  \"daysin_Cow\" \"count_Pig\"  \"dist_Pig\"   \"indor_Pig\" \n[21] \"daysin_Pig\" \"count_Dog\"  \"dist_Dog\"   \"indor_Dog\"  \"daysin_Dog\"\n[26] \"count_Oth\"  \"dist_Oth\"   \"indor_Oth\"  \"daysin_Oth\"\n```\n:::\n\n```{.r .cell-code .numberLines}\n#str(animals)\n#View(animals)\n\nanimals$indor_Pou[is.na(animals$indor_Pou)] <- 0\nanimals$indor_Pig[is.na(animals$indor_Pig)] <- 0\nanimals$indor_Oth[is.na(animals$indor_Oth)] <- 0\nanimals$indor_Goa[is.na(animals$indor_Goa)] <- 0\nanimals$indor_Dog[is.na(animals$indor_Dog)] <- 0\nanimals$indor_Cow[is.na(animals$indor_Cow)] <- 0\nanimals$indor_Buf[is.na(animals$indor_Buf)] <- 0\n\nanimals$daysin_Pou[is.na(animals$daysin_Pou) | animals$daysin_Pou == -1] <- 0\nanimals$daysin_Pig[is.na(animals$daysin_Pig) | animals$daysin_Pig == -1] <- 0\nanimals$daysin_Oth[is.na(animals$daysin_Oth) | animals$daysin_Oth == -1] <- 0\nanimals$daysin_Goa[is.na(animals$daysin_Goa) | animals$daysin_Goa == -1] <- 0\nanimals$daysin_Dog[is.na(animals$daysin_Dog) | animals$daysin_Dog == -1] <- 0\nanimals$daysin_Cow[is.na(animals$daysin_Cow) | animals$daysin_Cow == -1] <- 0\nanimals$daysin_Buf[is.na(animals$daysin_Buf) | animals$daysin_Buf == -1] <- 0\n\nanimals$count_Pou[is.na(animals$count_Pou)| animals$count_Pou == -1] <- 0\nanimals$count_Pig[is.na(animals$count_Pig)| animals$count_Pig == -1] <- 0\nanimals$count_Oth[is.na(animals$count_Oth)| animals$count_Oth == -1] <- 0\nanimals$count_Goa[is.na(animals$count_Goa)| animals$count_Goa == -1] <- 0\nanimals$count_Dog[is.na(animals$count_Dog)| animals$count_Dog == -1] <- 0\nanimals$count_Cow[is.na(animals$count_Cow)| animals$count_Cow == -1] <- 0\nanimals$count_Buf[is.na(animals$count_Buf)| animals$count_Buf == -1] <- 0\n\nstr(animals)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t7147 obs. of  29 variables:\n $ FSN       : int  45001 45002 45003 45004 45006 45009 45021 45024 45025 45027 ...\n $ count_Goa : num  3 0 0 2 0 7 1 3 3 0 ...\n $ dist_Goa  : int  5 NA NA 5 NA 0 5 15 0 NA ...\n $ indor_Goa : num  1 0 0 1 0 1 1 1 1 0 ...\n $ daysin_Goa: num  120 0 0 180 0 360 150 90 90 0 ...\n $ count_Pou : num  1 0 0 0 0 0 0 0 0 2 ...\n $ dist_Pou  : int  0 NA NA NA NA NA NA NA NA 0 ...\n $ indor_Pou : num  1 0 0 0 0 0 0 0 0 1 ...\n $ daysin_Pou: num  365 0 0 0 0 0 0 0 0 360 ...\n $ count_Buf : num  0 1 0 0 0 0 0 0 0 0 ...\n $ dist_Buf  : int  NA 4 NA NA NA NA NA NA NA NA ...\n $ indor_Buf : num  0 0 0 0 0 0 0 0 0 0 ...\n $ daysin_Buf: num  0 0 0 0 0 0 0 0 0 0 ...\n $ count_Cow : num  0 0 1 0 2 0 3 0 0 0 ...\n $ dist_Cow  : int  NA NA 3 NA 0 NA 15 NA NA NA ...\n $ indor_Cow : num  0 0 1 0 1 0 0 0 0 0 ...\n $ daysin_Cow: num  0 0 210 0 360 0 0 0 0 0 ...\n $ count_Pig : num  0 0 0 0 0 0 0 0 0 0 ...\n $ dist_Pig  : int  NA NA NA NA NA NA NA NA NA NA ...\n $ indor_Pig : num  0 0 0 0 0 0 0 0 0 0 ...\n $ daysin_Pig: num  0 0 0 0 0 0 0 0 0 0 ...\n $ count_Dog : num  0 0 0 0 0 0 0 0 0 0 ...\n $ dist_Dog  : int  NA NA NA NA NA NA NA NA NA NA ...\n $ indor_Dog : num  0 0 0 0 0 0 0 0 0 0 ...\n $ daysin_Dog: num  0 0 0 0 0 0 0 0 0 0 ...\n $ count_Oth : num  0 0 0 0 0 0 0 0 0 0 ...\n $ dist_Oth  : int  NA NA NA NA NA NA NA NA NA NA ...\n $ indor_Oth : num  0 0 0 0 0 0 0 0 0 0 ...\n $ daysin_Oth: num  0 0 0 0 0 0 0 0 0 0 ...\n - attr(*, \"reshapeWide\")=List of 5\n  ..$ v.names: chr [1:4] \"count\" \"dist\" \"indor\" \"daysin\"\n  ..$ timevar: chr \"anim\"\n  ..$ idvar  : chr \"FSN\"\n  ..$ times  : chr [1:7] \"Goa\" \"Pou\" \"Buf\" \"Cow\" ...\n  ..$ varying: chr [1:4, 1:7] \"count_Goa\" \"dist_Goa\" \"indor_Goa\" \"daysin_Goa\" ...\n```\n:::\n:::\n\n::: {.cell hash='The-case_cache/html/unnamed-chunk-17_ab3edc67f818629049ba0663ee63eede'}\n\n```{.r .cell-code .numberLines}\nsaveRDS(animals, \"animals.RDS\")\n```\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}