{
  "hash": "faa6deaedaf8dbc6f46313f81a2a95b5",
  "result": {
    "markdown": "---\ntitle: \"Data Cleaning\"\nformat: \n  html:\n    self-contained: true\n    code-line-numbers: true\n  pdf: \n    documentclass: article\ncustom_title_page: false\nfilters:\n  - lightbox\nlightbox: auto\n---\n\n---\nsubtitle: \"Data Cleaning\"\ndate: 2023-02-28\n\nauthor:\n  - name: Javier Silva-Valencia\n    orcid: 0000-0002-5982-2821\n    email: javier.silva@unmsm.edu.pe\n    affiliations:\n      - name: Instituut Voor Tropische Geneeskunde. Antwerp-Belgium\n\nlanguage: \n  title-block-author-single: \"Writer\"\n  \nabstract: We are going to follow the plan made in [The Analysis Plan](Analysis_Plan.qmd#Data Analysis Plan) to do the data cleaning\n---\n\n\n\n------------------------------------------------------------------------\n\n------------------------------------------------------------------------\n\n### Data Cleaning\n\n### 1. Reshape Q1_B\\_1\n\nThis dataset contains data of animals in household. We will reshape it so that each row should be a Household. We do that in order to merge with other datasets. Replace values if need it. (NA, -1)\n\n\n\n::: {.cell hash='Data-Analysis-Wk2_cache/pdf/unnamed-chunk-1_1f99b8bd6c40468d2d2260da72f341e5'}\n\n```{.r .cell-code .numberLines}\n#Use the dataset with the short name variables we worked before and save\nQ1_B_1 = readRDS(\"Q1_B_1.RDS\")\n```\n:::\n\n\n\n1.1 Reshaping from long to Wide\n\nWe need one line for each household.\n\nSo, we will use reshape command to say: \"Reshape the database taking in to account that i want to make the database wider, having just one line for each household (FSN) and replicating the variables count, dist, indor, daysin for every animal that the household had\"\n\n\n\n::: {.cell hash='Data-Analysis-Wk2_cache/pdf/unnamed-chunk-2_29a04f9f374936d3bf4ed80432775ae3'}\n\n```{.r .cell-code .numberLines}\nanimals <- reshape(Q1_B_1,direction = \"wide\", timevar =\"anim\", idvar =\"FSN\", v.names = c(\"count\",\"dist\",\"indor\", \"daysin\"), sep = \"_\")\nstr(animals)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t7147 obs. of  29 variables:\n $ FSN       : int  45001 45002 45003 45004 45006 45009 45021 45024 45025 45027 ...\n $ count_Goa : int  3 NA NA 2 NA 7 1 3 3 NA ...\n $ dist_Goa  : int  5 NA NA 5 NA 0 5 15 0 NA ...\n $ indor_Goa : int  1 NA NA 1 NA 1 1 1 1 NA ...\n $ daysin_Goa: int  120 NA NA 180 NA 360 150 90 90 NA ...\n $ count_Pou : int  1 NA NA NA NA NA NA NA NA 2 ...\n $ dist_Pou  : int  0 NA NA NA NA NA NA NA NA 0 ...\n $ indor_Pou : int  1 NA NA NA NA NA NA NA NA 1 ...\n $ daysin_Pou: int  365 NA NA NA NA NA NA NA NA 360 ...\n $ count_Buf : int  NA 1 NA NA NA NA NA NA NA NA ...\n $ dist_Buf  : int  NA 4 NA NA NA NA NA NA NA NA ...\n $ indor_Buf : int  NA 0 NA NA NA NA NA NA NA NA ...\n $ daysin_Buf: int  NA -1 NA NA NA NA NA NA NA NA ...\n $ count_Cow : int  NA NA 1 NA 2 NA 3 NA NA NA ...\n $ dist_Cow  : int  NA NA 3 NA 0 NA 15 NA NA NA ...\n $ indor_Cow : int  NA NA 1 NA 1 NA 0 NA NA NA ...\n $ daysin_Cow: int  NA NA 210 NA 360 NA -1 NA NA NA ...\n $ count_Pig : int  NA NA NA NA NA NA NA NA NA NA ...\n $ dist_Pig  : int  NA NA NA NA NA NA NA NA NA NA ...\n $ indor_Pig : int  NA NA NA NA NA NA NA NA NA NA ...\n $ daysin_Pig: int  NA NA NA NA NA NA NA NA NA NA ...\n $ count_Dog : int  NA NA NA NA NA NA NA NA NA NA ...\n $ dist_Dog  : int  NA NA NA NA NA NA NA NA NA NA ...\n $ indor_Dog : int  NA NA NA NA NA NA NA NA NA NA ...\n $ daysin_Dog: int  NA NA NA NA NA NA NA NA NA NA ...\n $ count_Oth : int  NA NA NA NA NA NA NA NA NA NA ...\n $ dist_Oth  : int  NA NA NA NA NA NA NA NA NA NA ...\n $ indor_Oth : int  NA NA NA NA NA NA NA NA NA NA ...\n $ daysin_Oth: int  NA NA NA NA NA NA NA NA NA NA ...\n - attr(*, \"reshapeWide\")=List of 5\n  ..$ v.names: chr [1:4] \"count\" \"dist\" \"indor\" \"daysin\"\n  ..$ timevar: chr \"anim\"\n  ..$ idvar  : chr \"FSN\"\n  ..$ times  : chr [1:7] \"Goa\" \"Pou\" \"Buf\" \"Cow\" ...\n  ..$ varying: chr [1:4, 1:7] \"count_Goa\" \"dist_Goa\" \"indor_Goa\" \"daysin_Goa\" ...\n```\n:::\n\n```{.r .cell-code .numberLines}\nclass(animals)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"data.frame\"\n```\n:::\n\n```{.r .cell-code .numberLines}\n#View(animals)\n```\n:::\n\n\n\n::: callout-tip\nWe observe:\n\n-   That now we have less observations (7147)(before was 9029 obs)\n\n-   There are a lot of NA (households than doesn't have that animal)\n\n-    There are also some -1 values\n:::\n\n1.2 Replacing innnecesary values\n\nWe want to replace the NA and the -1 to Zero in all columns\n\n\n\n::: {.cell hash='Data-Analysis-Wk2_cache/pdf/unnamed-chunk-3_269fb854ed25b41c932e9ac7cf87ccbc'}\n\n```{.r .cell-code .numberLines}\nnames(animals)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] \"FSN\"        \"count_Goa\"  \"dist_Goa\"   \"indor_Goa\"  \"daysin_Goa\"\n [6] \"count_Pou\"  \"dist_Pou\"   \"indor_Pou\"  \"daysin_Pou\" \"count_Buf\" \n[11] \"dist_Buf\"   \"indor_Buf\"  \"daysin_Buf\" \"count_Cow\"  \"dist_Cow\"  \n[16] \"indor_Cow\"  \"daysin_Cow\" \"count_Pig\"  \"dist_Pig\"   \"indor_Pig\" \n[21] \"daysin_Pig\" \"count_Dog\"  \"dist_Dog\"   \"indor_Dog\"  \"daysin_Dog\"\n[26] \"count_Oth\"  \"dist_Oth\"   \"indor_Oth\"  \"daysin_Oth\"\n```\n:::\n\n```{.r .cell-code .numberLines}\n#str(animals)\n#View(animals)\n\nanimals$indor_Pou[is.na(animals$indor_Pou)] <- 0\nanimals$indor_Pig[is.na(animals$indor_Pig)] <- 0\nanimals$indor_Oth[is.na(animals$indor_Oth)] <- 0\nanimals$indor_Goa[is.na(animals$indor_Goa)] <- 0\nanimals$indor_Dog[is.na(animals$indor_Dog)] <- 0\nanimals$indor_Cow[is.na(animals$indor_Cow)] <- 0\nanimals$indor_Buf[is.na(animals$indor_Buf)] <- 0\n\nanimals$daysin_Pou[is.na(animals$daysin_Pou) | animals$daysin_Pou == -1] <- 0\nanimals$daysin_Pig[is.na(animals$daysin_Pig) | animals$daysin_Pig == -1] <- 0\nanimals$daysin_Oth[is.na(animals$daysin_Oth) | animals$daysin_Oth == -1] <- 0\nanimals$daysin_Goa[is.na(animals$daysin_Goa) | animals$daysin_Goa == -1] <- 0\nanimals$daysin_Dog[is.na(animals$daysin_Dog) | animals$daysin_Dog == -1] <- 0\nanimals$daysin_Cow[is.na(animals$daysin_Cow) | animals$daysin_Cow == -1] <- 0\nanimals$daysin_Buf[is.na(animals$daysin_Buf) | animals$daysin_Buf == -1] <- 0\n\nanimals$count_Pou[is.na(animals$count_Pou)| animals$count_Pou == -1] <- 0\nanimals$count_Pig[is.na(animals$count_Pig)| animals$count_Pig == -1] <- 0\nanimals$count_Oth[is.na(animals$count_Oth)| animals$count_Oth == -1] <- 0\nanimals$count_Goa[is.na(animals$count_Goa)| animals$count_Goa == -1] <- 0\nanimals$count_Dog[is.na(animals$count_Dog)| animals$count_Dog == -1] <- 0\nanimals$count_Cow[is.na(animals$count_Cow)| animals$count_Cow == -1] <- 0\nanimals$count_Buf[is.na(animals$count_Buf)| animals$count_Buf == -1] <- 0\n\nstr(animals)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t7147 obs. of  29 variables:\n $ FSN       : int  45001 45002 45003 45004 45006 45009 45021 45024 45025 45027 ...\n $ count_Goa : num  3 0 0 2 0 7 1 3 3 0 ...\n $ dist_Goa  : int  5 NA NA 5 NA 0 5 15 0 NA ...\n $ indor_Goa : num  1 0 0 1 0 1 1 1 1 0 ...\n $ daysin_Goa: num  120 0 0 180 0 360 150 90 90 0 ...\n $ count_Pou : num  1 0 0 0 0 0 0 0 0 2 ...\n $ dist_Pou  : int  0 NA NA NA NA NA NA NA NA 0 ...\n $ indor_Pou : num  1 0 0 0 0 0 0 0 0 1 ...\n $ daysin_Pou: num  365 0 0 0 0 0 0 0 0 360 ...\n $ count_Buf : num  0 1 0 0 0 0 0 0 0 0 ...\n $ dist_Buf  : int  NA 4 NA NA NA NA NA NA NA NA ...\n $ indor_Buf : num  0 0 0 0 0 0 0 0 0 0 ...\n $ daysin_Buf: num  0 0 0 0 0 0 0 0 0 0 ...\n $ count_Cow : num  0 0 1 0 2 0 3 0 0 0 ...\n $ dist_Cow  : int  NA NA 3 NA 0 NA 15 NA NA NA ...\n $ indor_Cow : num  0 0 1 0 1 0 0 0 0 0 ...\n $ daysin_Cow: num  0 0 210 0 360 0 0 0 0 0 ...\n $ count_Pig : num  0 0 0 0 0 0 0 0 0 0 ...\n $ dist_Pig  : int  NA NA NA NA NA NA NA NA NA NA ...\n $ indor_Pig : num  0 0 0 0 0 0 0 0 0 0 ...\n $ daysin_Pig: num  0 0 0 0 0 0 0 0 0 0 ...\n $ count_Dog : num  0 0 0 0 0 0 0 0 0 0 ...\n $ dist_Dog  : int  NA NA NA NA NA NA NA NA NA NA ...\n $ indor_Dog : num  0 0 0 0 0 0 0 0 0 0 ...\n $ daysin_Dog: num  0 0 0 0 0 0 0 0 0 0 ...\n $ count_Oth : num  0 0 0 0 0 0 0 0 0 0 ...\n $ dist_Oth  : int  NA NA NA NA NA NA NA NA NA NA ...\n $ indor_Oth : num  0 0 0 0 0 0 0 0 0 0 ...\n $ daysin_Oth: num  0 0 0 0 0 0 0 0 0 0 ...\n - attr(*, \"reshapeWide\")=List of 5\n  ..$ v.names: chr [1:4] \"count\" \"dist\" \"indor\" \"daysin\"\n  ..$ timevar: chr \"anim\"\n  ..$ idvar  : chr \"FSN\"\n  ..$ times  : chr [1:7] \"Goa\" \"Pou\" \"Buf\" \"Cow\" ...\n  ..$ varying: chr [1:4, 1:7] \"count_Goa\" \"dist_Goa\" \"indor_Goa\" \"daysin_Goa\" ...\n```\n:::\n:::\n\n\n\n\n\n### 2. Create an asset index\n\nThis index should include information of consumer goods, as well if having a bovine animal and if having a brick wall household.\n\n#### 2.1. Select consumer goods\n\nSelect the consumer goods (from Q1_B_106 dataset) that will conform the asset.\n\n2.1.1. Importing the CSV database under the name of Q1_B\\_106, with \",\" as separator, and with \".\" as decimal:\n\n\n\n::: {.cell hash='Data-Analysis-Wk2_cache/pdf/unnamed-chunk-4_8a951eb49631d159c001a5a8fb157e72'}\n\n```{.r .cell-code .numberLines}\nQ1_B_106 <- read.csv(\"C:/Users/pined/OneDrive - Universidad Nacional Mayor de San Marcos/Javier 2022/Belgica/AC2_DataAnalysis_ThWk/Material/Q1_B_106.csv\", sep=\",\", dec= \".\")\n```\n:::\n\n\n\n2.1.2. Seeing the structure and values of the dataset\n\n\n\n::: {.cell hash='Data-Analysis-Wk2_cache/pdf/unnamed-chunk-5_3ab2b6809d99df4627c7cf6bae02f55d'}\n\n```{.r .cell-code .numberLines}\nstr(Q1_B_106)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t13377 obs. of  25 variables:\n $ FSN             : int  45001 45002 45003 45004 45005 45006 45007 45008 45009 45010 ...\n $ Radio           : int  1 1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ CD_Player       : int  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ BW_Television   : int  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Color_Television: int  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Video_DVD_Player: int  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Mobile          : int  -1 -1 -1 -1 -1 1 -1 -1 -1 -1 ...\n $ Non_Mobile_Phone: int  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Refrigerator    : int  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Iron            : int  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Sewing_Machine  : int  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Watch           : int  -1 -1 -1 -1 -1 1 -1 -1 -1 -1 ...\n $ Pressure_Cooker : int  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Chairs          : int  1 -1 -1 -1 1 1 -1 -1 2 -1 ...\n $ Sofas           : int  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Tables          : int  -1 -1 -1 -1 -1 1 -1 -1 -1 -1 ...\n $ Cot_Bed         : int  2 2 3 -1 2 1 2 1 2 -1 ...\n $ Cupboards       : int  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Bicycle         : int  1 1 1 -1 -1 2 -1 -1 1 -1 ...\n $ Motor_Cycle     : int  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Animal_Draw_Cart: int  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Car             : int  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Tractor         : int  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Computer        : int  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Electric_Fan    : int  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n```\n:::\n:::\n\n\n\n::: callout-tip\nAccording to dictionary\n\n-1 : Missing or not available\n\n0, 1, 2, 3 : Number of items they have\n:::\n\n2.1.3. Checking the summary of the variables \n\n\n\n::: {.cell hash='Data-Analysis-Wk2_cache/pdf/unnamed-chunk-6_d7b1c0063a6edc69bc191173925790ef'}\n\n```{.r .cell-code .numberLines}\nsummary(Q1_B_106)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n      FSN            Radio           CD_Player       BW_Television    \n Min.   :45001   Min.   :-1.0000   Min.   :-1.0000   Min.   :-1.0000  \n 1st Qu.:48527   1st Qu.:-1.0000   1st Qu.:-1.0000   1st Qu.:-1.0000  \n Median :52032   Median :-1.0000   Median :-1.0000   Median :-1.0000  \n Mean   :52110   Mean   :-0.7555   Mean   :-0.9517   Mean   :-0.9015  \n 3rd Qu.:55671   3rd Qu.:-1.0000   3rd Qu.:-1.0000   3rd Qu.:-1.0000  \n Max.   :59606   Max.   : 6.0000   Max.   : 3.0000   Max.   : 2.0000  \n Color_Television  Video_DVD_Player      Mobile         Non_Mobile_Phone \n Min.   :-1.0000   Min.   :-1.0000   Min.   :-1.00000   Min.   :-1.0000  \n 1st Qu.:-1.0000   1st Qu.:-1.0000   1st Qu.:-1.00000   1st Qu.:-1.0000  \n Median :-1.0000   Median :-1.0000   Median :-1.00000   Median :-1.0000  \n Mean   :-0.9217   Mean   :-0.9785   Mean   : 0.01323   Mean   :-0.9885  \n 3rd Qu.:-1.0000   3rd Qu.:-1.0000   3rd Qu.: 1.00000   3rd Qu.:-1.0000  \n Max.   : 2.0000   Max.   : 1.0000   Max.   :10.00000   Max.   : 1.0000  \n  Refrigerator          Iron         Sewing_Machine        Watch        \n Min.   :-1.0000   Min.   :-1.0000   Min.   :-1.0000   Min.   :-1.0000  \n 1st Qu.:-1.0000   1st Qu.:-1.0000   1st Qu.:-1.0000   1st Qu.:-1.0000  \n Median :-1.0000   Median :-1.0000   Median :-1.0000   Median :-1.0000  \n Mean   :-0.9937   Mean   :-0.9415   Mean   :-0.8969   Mean   :-0.3998  \n 3rd Qu.:-1.0000   3rd Qu.:-1.0000   3rd Qu.:-1.0000   3rd Qu.: 1.0000  \n Max.   : 1.0000   Max.   : 4.0000   Max.   : 3.0000   Max.   :12.0000  \n Pressure_Cooker       Chairs            Sofas             Tables       \n Min.   :-1.0000   Min.   :-1.0000   Min.   :-1.0000   Min.   :-1.0000  \n 1st Qu.:-1.0000   1st Qu.:-1.0000   1st Qu.:-1.0000   1st Qu.:-1.0000  \n Median :-1.0000   Median :-1.0000   Median :-1.0000   Median :-1.0000  \n Mean   :-0.8435   Mean   : 0.4572   Mean   :-0.9602   Mean   :-0.2501  \n 3rd Qu.:-1.0000   3rd Qu.: 2.0000   3rd Qu.:-1.0000   3rd Qu.: 1.0000  \n Max.   : 5.0000   Max.   :40.0000   Max.   : 8.0000   Max.   :10.0000  \n    Cot_Bed         Cupboards          Bicycle          Motor_Cycle     \n Min.   :-1.000   Min.   :-1.0000   Min.   :-1.00000   Min.   :-1.0000  \n 1st Qu.: 2.000   1st Qu.:-1.0000   1st Qu.:-1.00000   1st Qu.:-1.0000  \n Median : 2.000   Median :-1.0000   Median : 1.00000   Median :-1.0000  \n Mean   : 2.599   Mean   :-0.9624   Mean   : 0.09793   Mean   :-0.8656  \n 3rd Qu.: 3.000   3rd Qu.:-1.0000   3rd Qu.: 1.00000   3rd Qu.:-1.0000  \n Max.   :24.000   Max.   : 7.0000   Max.   : 6.00000   Max.   : 5.0000  \n Animal_Draw_Cart       Car             Tractor           Computer      \n Min.   :-1.0000   Min.   :-1.0000   Min.   :-1.0000   Min.   :-1.0000  \n 1st Qu.:-1.0000   1st Qu.:-1.0000   1st Qu.:-1.0000   1st Qu.:-1.0000  \n Median :-1.0000   Median :-1.0000   Median :-1.0000   Median :-1.0000  \n Mean   :-0.9919   Mean   :-0.9938   Mean   :-0.9874   Mean   :-0.9982  \n 3rd Qu.:-1.0000   3rd Qu.:-1.0000   3rd Qu.:-1.0000   3rd Qu.:-1.0000  \n Max.   : 1.0000   Max.   : 2.0000   Max.   : 3.0000   Max.   : 1.0000  \n  Electric_Fan    \n Min.   :-1.0000  \n 1st Qu.:-1.0000  \n Median :-1.0000  \n Mean   :-0.6872  \n 3rd Qu.:-1.0000  \n Max.   :11.0000  \n```\n:::\n:::\n\n\n\n::: callout-tip\nExample of what we can see: The maximum number of radios in a household is 6\n:::\n\n\n2.1.4. Transform to dichotomous variables\n\nWe need that all '-1' be converting to '0'. \n\nand all value more than '≥ 1' be converting to '1'\n\n\n\n::: {.cell hash='Data-Analysis-Wk2_cache/pdf/unnamed-chunk-7_c9123a2b9e279e87aaa0437a46b68732'}\n\n```{.r .cell-code .numberLines}\n#We can do it by using \"if else\":\nQ1_B_106$own_Radio <- ifelse(Q1_B_106$Radio>0,1,0)\n\n\n#But other way is: \n#Q1_B_106$own_Radio <- as.numeric(Q1_B_106$Radio > 0)\n#Ask to create a variable called \"own_Radio\" only TRUE when \"Radio\" is more than 0 and converting that into a number (as.numeric) (1:true,0:false)\n\n\n#Checking if it works\ntable(Q1_B_106$own_Radio, Q1_B_106$Radio, useNA = \"always\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n      \n          -1     1     2     3     6  <NA>\n  0    11753     0     0     0     0     0\n  1        0  1608    12     3     1     0\n  <NA>     0     0     0     0     0     0\n```\n:::\n\n```{.r .cell-code .numberLines}\nsummary(Q1_B_106$own_Radio)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n 0.0000  0.0000  0.0000  0.1214  0.0000  1.0000 \n```\n:::\n:::\n\n\n\n::: callout-tip\nAs a result we can see that: 12.14% of households have at least one radio. Remember: When we only have 0 and 1, The mean of the variable is the proportion of individuals having the exposure.\n:::\n\nWe need to do that for every variable\n\n\n\n::: {.cell hash='Data-Analysis-Wk2_cache/pdf/unnamed-chunk-8_62b506decae7412e4eca678c3cb35f86'}\n\n```{.r .cell-code .numberLines}\nQ1_B_106$own_Radio <- ifelse(Q1_B_106$Radio>0,1,0)\nQ1_B_106$own_CD_Player <- ifelse(Q1_B_106$CD_Player>0,1,0)\nQ1_B_106$own_BW_Television <- ifelse(Q1_B_106$BW_Television>0,1,0)\nQ1_B_106$own_Color_Television <- ifelse(Q1_B_106$Color_Television>0,1,0)\nQ1_B_106$own_Video_DVD_Player <- ifelse(Q1_B_106$Video_DVD_Player>0,1,0)\nQ1_B_106$own_Mobile <- ifelse(Q1_B_106$Mobile>0,1,0)\nQ1_B_106$own_Non_Mobile_Phone <- ifelse(Q1_B_106$Non_Mobile_Phone>0,1,0)\nQ1_B_106$own_Refrigerator <- ifelse(Q1_B_106$Refrigerator>0,1,0)\nQ1_B_106$own_Iron <- ifelse(Q1_B_106$Iron>0,1,0)\nQ1_B_106$own_Sewing_Machine <- ifelse(Q1_B_106$Sewing_Machine>0,1,0)\nQ1_B_106$own_Watch <- ifelse(Q1_B_106$Watch>0,1,0)\nQ1_B_106$own_Pressure_Cooker <- ifelse(Q1_B_106$Pressure_Cooker>0,1,0)\nQ1_B_106$own_Chairs <- ifelse(Q1_B_106$Chairs>0,1,0)\nQ1_B_106$own_Sofas <- ifelse(Q1_B_106$Sofas>0,1,0)\nQ1_B_106$own_Tables <- ifelse(Q1_B_106$Tables>0,1,0)\nQ1_B_106$own_Cot_Bed <- ifelse(Q1_B_106$Cot_Bed>0,1,0)\nQ1_B_106$own_Cupboards <- ifelse(Q1_B_106$Cupboards>0,1,0)\nQ1_B_106$own_Bicycle <- ifelse(Q1_B_106$Bicycle>0,1,0)\nQ1_B_106$own_Motor_Cycle <- ifelse(Q1_B_106$Motor_Cycle>0,1,0)\nQ1_B_106$own_Animal_Draw_Cart <- ifelse(Q1_B_106$Animal_Draw_Cart>0,1,0)\nQ1_B_106$own_Car <- ifelse(Q1_B_106$Car>0,1,0)\nQ1_B_106$own_Tractor <- ifelse(Q1_B_106$Tractor>0,1,0)\nQ1_B_106$own_Computer <- ifelse(Q1_B_106$Computer>0,1,0)\nQ1_B_106$own_Electric_Fan <- ifelse(Q1_B_106$Electric_Fan>0,1,0)\n```\n:::\n\n\n\n2.1.5. Now we will make a subset containing only the 'own' variables and FSN\n\n\n\n::: {.cell hash='Data-Analysis-Wk2_cache/pdf/unnamed-chunk-9_ceb9f668888bd1c057e3a1e0a3bd4f4e'}\n\n```{.r .cell-code .numberLines}\nassets <- subset(Q1_B_106, select = grepl(\"own|FSN\", names(Q1_B_106)))\nstr(assets)  \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t13377 obs. of  25 variables:\n $ FSN                 : int  45001 45002 45003 45004 45005 45006 45007 45008 45009 45010 ...\n $ own_Radio           : num  1 1 0 0 0 0 0 0 0 0 ...\n $ own_CD_Player       : num  0 0 0 0 0 0 0 0 0 0 ...\n $ own_BW_Television   : num  0 0 0 0 0 0 0 0 0 0 ...\n $ own_Color_Television: num  0 0 0 0 0 0 0 0 0 0 ...\n $ own_Video_DVD_Player: num  0 0 0 0 0 0 0 0 0 0 ...\n $ own_Mobile          : num  0 0 0 0 0 1 0 0 0 0 ...\n $ own_Non_Mobile_Phone: num  0 0 0 0 0 0 0 0 0 0 ...\n $ own_Refrigerator    : num  0 0 0 0 0 0 0 0 0 0 ...\n $ own_Iron            : num  0 0 0 0 0 0 0 0 0 0 ...\n $ own_Sewing_Machine  : num  0 0 0 0 0 0 0 0 0 0 ...\n $ own_Watch           : num  0 0 0 0 0 1 0 0 0 0 ...\n $ own_Pressure_Cooker : num  0 0 0 0 0 0 0 0 0 0 ...\n $ own_Chairs          : num  1 0 0 0 1 1 0 0 1 0 ...\n $ own_Sofas           : num  0 0 0 0 0 0 0 0 0 0 ...\n $ own_Tables          : num  0 0 0 0 0 1 0 0 0 0 ...\n $ own_Cot_Bed         : num  1 1 1 0 1 1 1 1 1 0 ...\n $ own_Cupboards       : num  0 0 0 0 0 0 0 0 0 0 ...\n $ own_Bicycle         : num  1 1 1 0 0 1 0 0 1 0 ...\n $ own_Motor_Cycle     : num  0 0 0 0 0 0 0 0 0 0 ...\n $ own_Animal_Draw_Cart: num  0 0 0 0 0 0 0 0 0 0 ...\n $ own_Car             : num  0 0 0 0 0 0 0 0 0 0 ...\n $ own_Tractor         : num  0 0 0 0 0 0 0 0 0 0 ...\n $ own_Computer        : num  0 0 0 0 0 0 0 0 0 0 ...\n $ own_Electric_Fan    : num  0 0 0 0 0 0 0 0 0 0 ...\n```\n:::\n:::\n\n\n\n2.1.6. Now we will focus only in those variables whose mean have a value between 5-95% (0.05-0.95)\n\nwhy?: Because We are going to exclude the variables that nobody has (less than 5%) and the variables that all people has (more than 95%)\n\n\n\n::: {.cell hash='Data-Analysis-Wk2_cache/pdf/unnamed-chunk-10_5e80010e96254bf922e592c97f1ac93e'}\n\n```{.r .cell-code .numberLines}\n#summary(assets)\nround(sapply(assets, FUN=mean),3)   #To display the mean of each variable with 3 decimals\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                 FSN            own_Radio        own_CD_Player \n           52110.000                0.121                0.024 \n   own_BW_Television own_Color_Television own_Video_DVD_Player \n               0.049                0.039                0.011 \n          own_Mobile own_Non_Mobile_Phone     own_Refrigerator \n               0.476                0.006                0.003 \n            own_Iron   own_Sewing_Machine            own_Watch \n               0.028                0.051                0.264 \n own_Pressure_Cooker           own_Chairs            own_Sofas \n               0.072                0.429                0.017 \n          own_Tables          own_Cot_Bed        own_Cupboards \n               0.329                0.968                0.013 \n         own_Bicycle      own_Motor_Cycle own_Animal_Draw_Cart \n               0.524                0.065                0.004 \n             own_Car          own_Tractor         own_Computer \n               0.003                0.006                0.001 \n    own_Electric_Fan \n               0.110 \n```\n:::\n:::\n\n\n\n::: callout-tip\nBesides FSN, 10 variables have a value between 5-95% (0.05-0.95)\n:::\n\n2.1.7. We are going to create a new subset (assets2) with only in those variables whose mean have a value between 5-95% (0.05-0.95)\n\n\n\n::: {.cell hash='Data-Analysis-Wk2_cache/pdf/unnamed-chunk-11_8c2b064c194bbd33ffbfcf72e502ab2c'}\n\n```{.r .cell-code .numberLines}\nassets2 <- subset(assets, select = c(FSN, own_Radio,own_Mobile, own_Sewing_Machine, own_Watch, own_Pressure_Cooker, own_Chairs, own_Tables, own_Bicycle, own_Motor_Cycle, own_Electric_Fan))\nstr(assets2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t13377 obs. of  11 variables:\n $ FSN                : int  45001 45002 45003 45004 45005 45006 45007 45008 45009 45010 ...\n $ own_Radio          : num  1 1 0 0 0 0 0 0 0 0 ...\n $ own_Mobile         : num  0 0 0 0 0 1 0 0 0 0 ...\n $ own_Sewing_Machine : num  0 0 0 0 0 0 0 0 0 0 ...\n $ own_Watch          : num  0 0 0 0 0 1 0 0 0 0 ...\n $ own_Pressure_Cooker: num  0 0 0 0 0 0 0 0 0 0 ...\n $ own_Chairs         : num  1 0 0 0 1 1 0 0 1 0 ...\n $ own_Tables         : num  0 0 0 0 0 1 0 0 0 0 ...\n $ own_Bicycle        : num  1 1 1 0 0 1 0 0 1 0 ...\n $ own_Motor_Cycle    : num  0 0 0 0 0 0 0 0 0 0 ...\n $ own_Electric_Fan   : num  0 0 0 0 0 0 0 0 0 0 ...\n```\n:::\n:::\n\n\n\n\n#### 2.2. Create own_bovine variable\n\nUse the previously created \"animals\" dataset to create a variable of owning a bovine animal.\n\nThe researchers noticed that having a \"bovines animals\" variable is important, so we need to incorporate it. The only problem is that the animals information is in another dataset.\n\n'own_bov' for each household = whether or not it owns cows or buffaloes\n\n\n\n::: {.cell hash='Data-Analysis-Wk2_cache/pdf/unnamed-chunk-12_9dd372b1b6ae9939fea326644a52bd4c'}\n\n```{.r .cell-code .numberLines}\nhlp1 <- subset(animals, select=c(FSN, count_Cow, count_Buf))\nhlp1$own_bov <- NA\nhlp1$own_bov[hlp1$count_Cow== 0 & hlp1$count_Buf==0] <- 0\nhlp1$own_bov[hlp1$count_Cow> 0 | hlp1$count_Buf>0] <- 1 \nstr(hlp1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t7147 obs. of  4 variables:\n $ FSN      : int  45001 45002 45003 45004 45006 45009 45021 45024 45025 45027 ...\n $ count_Cow: num  0 0 1 0 2 0 3 0 0 0 ...\n $ count_Buf: num  0 1 0 0 0 0 0 0 0 0 ...\n $ own_bov  : num  0 1 1 0 1 0 1 0 0 0 ...\n```\n:::\n:::\n\n\n\n\n#### 2.3. Create brickwall variable\n\nUse the Q1_B dataset to create a variable if the household have brickwalls.\n\nThe researchers also noticed that having a \"brick_wall\" variable is important, so we need to incorporate it. The only problem is that the brick_wall information is in another dataset.\n\n2.3.1. Opening Q1_B dataset\n\n\n\n::: {.cell hash='Data-Analysis-Wk2_cache/pdf/unnamed-chunk-13_b9d8806ff57018eb73fe90e02f3d1a2d'}\n\n```{.r .cell-code .numberLines}\nQ1_B <- read.csv(\"C:/Users/pined/OneDrive - Universidad Nacional Mayor de San Marcos/Javier 2022/Belgica/AC2_DataAnalysis_ThWk/Material/Q1_B.csv\", sep=\",\", dec= \".\")\n```\n:::\n\n\n\n2.3.2. Checking the variable Wall_Material in the Q1_B dataset\n\n\n\n::: {.cell hash='Data-Analysis-Wk2_cache/pdf/unnamed-chunk-14_357d53a63df3c651d455f45b8cb7e602'}\n\n```{.r .cell-code .numberLines}\ntable(Q1_B$Wall_Material)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n   6  162  163  164  165  166 \n   4 4498  169 5791 2914    1 \n```\n:::\n:::\n\n\n\n::: callout-tip\nAccording the code list:\n\n    6= Other\n    163= Grass\n    163= Bamboo\n    164, 165, 166= Brick\n\nSo we only need those who had the value 164 or 165 in the Wall_Material variable\n:::\n\n2.3.3. I only need \"FSN\" and \"WallMaterial\" variables\n\n\n\n::: {.cell hash='Data-Analysis-Wk2_cache/pdf/unnamed-chunk-15_c580d560a9565c8f73573bfd4b5013f2'}\n\n```{.r .cell-code .numberLines}\nhlp2 <- subset(Q1_B, select = c(FSN, Wall_Material))\n```\n:::\n\n\n\n2.3.4. Creating a new variable called brickwall according to what I need\n\n\n\n::: {.cell hash='Data-Analysis-Wk2_cache/pdf/unnamed-chunk-16_47efda662ea16d8296225b6ef023958a'}\n\n```{.r .cell-code .numberLines}\nhlp2$brick_wall <- NA\nhlp2$brick_wall[hlp2$Wall_Material %in% c(6,162,163)] <- 0\nhlp2$brick_wall[hlp2$Wall_Material %in% c(164:166)] <- 1\n\ntable(hlp2$brick_wall, Q1_B$Wall_Material)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   \n       6  162  163  164  165  166\n  0    4 4498  169    0    0    0\n  1    0    0    0 5791 2914    1\n```\n:::\n:::\n\n\n\n\n\n#### 2.4. Merging datasets\n\nMerge all this datasets in order to create the asset index\n\n![Merging planning](mergingdatsets.png)\n\n2.4.1. Merging hlp1 and hlp2\n\n\n\n::: {.cell hash='Data-Analysis-Wk2_cache/pdf/unnamed-chunk-17_2632dec85fddd50c8c0de51acaed40c1'}\n\n```{.r .cell-code .numberLines}\nstr(hlp1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t7147 obs. of  4 variables:\n $ FSN      : int  45001 45002 45003 45004 45006 45009 45021 45024 45025 45027 ...\n $ count_Cow: num  0 0 1 0 2 0 3 0 0 0 ...\n $ count_Buf: num  0 1 0 0 0 0 0 0 0 0 ...\n $ own_bov  : num  0 1 1 0 1 0 1 0 0 0 ...\n```\n:::\n\n```{.r .cell-code .numberLines}\nstr(hlp2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t13377 obs. of  3 variables:\n $ FSN          : num  45001 45002 45003 45004 45005 ...\n $ Wall_Material: num  164 164 164 162 163 163 162 164 164 162 ...\n $ brick_wall   : num  1 1 1 0 0 0 0 1 1 0 ...\n```\n:::\n\n```{.r .cell-code .numberLines}\nhlp  <-  merge(hlp2, hlp1, all=TRUE, by = \"FSN\")\nstr(hlp)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t13377 obs. of  6 variables:\n $ FSN          : num  45001 45002 45003 45004 45005 ...\n $ Wall_Material: num  164 164 164 162 163 163 162 164 164 162 ...\n $ brick_wall   : num  1 1 1 0 0 0 0 1 1 0 ...\n $ count_Cow    : num  0 0 1 0 NA 2 NA NA 0 NA ...\n $ count_Buf    : num  0 1 0 0 NA 0 NA NA 0 NA ...\n $ own_bov      : num  0 1 1 0 NA 1 NA NA 0 NA ...\n```\n:::\n\n```{.r .cell-code .numberLines}\n#View(hlp)\n```\n:::\n\n\n\nwe Dont need countCow, count_Buf or Wall_Material\n\n\n\n::: {.cell hash='Data-Analysis-Wk2_cache/pdf/unnamed-chunk-18_ef96f8a2cdf1b831fd7b11a959e1f6f3'}\n\n```{.r .cell-code .numberLines}\nhlp <- subset(hlp, select=-c(count_Cow,count_Buf,Wall_Material))\nstr(hlp)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t13377 obs. of  3 variables:\n $ FSN       : num  45001 45002 45003 45004 45005 ...\n $ brick_wall: num  1 1 1 0 0 0 0 1 1 0 ...\n $ own_bov   : num  0 1 1 0 NA 1 NA NA 0 NA ...\n```\n:::\n:::\n\n\n\n2.4.2. Merging hlp2 to assets2\n\n\n\n::: {.cell hash='Data-Analysis-Wk2_cache/pdf/unnamed-chunk-19_384f2647e2fb72806b6f4f7b8876fb10'}\n\n```{.r .cell-code .numberLines}\nstr(hlp)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t13377 obs. of  3 variables:\n $ FSN       : num  45001 45002 45003 45004 45005 ...\n $ brick_wall: num  1 1 1 0 0 0 0 1 1 0 ...\n $ own_bov   : num  0 1 1 0 NA 1 NA NA 0 NA ...\n```\n:::\n\n```{.r .cell-code .numberLines}\nstr(assets2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t13377 obs. of  11 variables:\n $ FSN                : int  45001 45002 45003 45004 45005 45006 45007 45008 45009 45010 ...\n $ own_Radio          : num  1 1 0 0 0 0 0 0 0 0 ...\n $ own_Mobile         : num  0 0 0 0 0 1 0 0 0 0 ...\n $ own_Sewing_Machine : num  0 0 0 0 0 0 0 0 0 0 ...\n $ own_Watch          : num  0 0 0 0 0 1 0 0 0 0 ...\n $ own_Pressure_Cooker: num  0 0 0 0 0 0 0 0 0 0 ...\n $ own_Chairs         : num  1 0 0 0 1 1 0 0 1 0 ...\n $ own_Tables         : num  0 0 0 0 0 1 0 0 0 0 ...\n $ own_Bicycle        : num  1 1 1 0 0 1 0 0 1 0 ...\n $ own_Motor_Cycle    : num  0 0 0 0 0 0 0 0 0 0 ...\n $ own_Electric_Fan   : num  0 0 0 0 0 0 0 0 0 0 ...\n```\n:::\n\n```{.r .cell-code .numberLines}\nassets3  <-  merge(assets2, hlp, all=TRUE, by = \"FSN\")\nstr(assets3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t13377 obs. of  13 variables:\n $ FSN                : int  45001 45002 45003 45004 45005 45006 45007 45008 45009 45010 ...\n $ own_Radio          : num  1 1 0 0 0 0 0 0 0 0 ...\n $ own_Mobile         : num  0 0 0 0 0 1 0 0 0 0 ...\n $ own_Sewing_Machine : num  0 0 0 0 0 0 0 0 0 0 ...\n $ own_Watch          : num  0 0 0 0 0 1 0 0 0 0 ...\n $ own_Pressure_Cooker: num  0 0 0 0 0 0 0 0 0 0 ...\n $ own_Chairs         : num  1 0 0 0 1 1 0 0 1 0 ...\n $ own_Tables         : num  0 0 0 0 0 1 0 0 0 0 ...\n $ own_Bicycle        : num  1 1 1 0 0 1 0 0 1 0 ...\n $ own_Motor_Cycle    : num  0 0 0 0 0 0 0 0 0 0 ...\n $ own_Electric_Fan   : num  0 0 0 0 0 0 0 0 0 0 ...\n $ brick_wall         : num  1 1 1 0 0 0 0 1 1 0 ...\n $ own_bov            : num  0 1 1 0 NA 1 NA NA 0 NA ...\n```\n:::\n\n```{.r .cell-code .numberLines}\n#View(assets3)\n```\n:::\n\n\n\n2.4.3. Check NA values\n\nThe merging creates NA values (ex: in own_bov), but that values are because that household doesnt have a bovine animal, so it should be 0\n\nChecking NA\n\n\n\n::: {.cell hash='Data-Analysis-Wk2_cache/pdf/unnamed-chunk-20_322784b5a79672adab0b8181d1d5604c'}\n\n```{.r .cell-code .numberLines}\ntable (assets3$own_bov)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n   0    1 \n2816 4331 \n```\n:::\n\n```{.r .cell-code .numberLines}\ntable (assets3$own_bov, useNA = \"ifany\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n   0    1 <NA> \n2816 4331 6230 \n```\n:::\n\n```{.r .cell-code .numberLines}\ntable (assets3$own_bov, useNA = \"always\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n   0    1 <NA> \n2816 4331 6230 \n```\n:::\n\n```{.r .cell-code .numberLines}\nstr(assets3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t13377 obs. of  13 variables:\n $ FSN                : int  45001 45002 45003 45004 45005 45006 45007 45008 45009 45010 ...\n $ own_Radio          : num  1 1 0 0 0 0 0 0 0 0 ...\n $ own_Mobile         : num  0 0 0 0 0 1 0 0 0 0 ...\n $ own_Sewing_Machine : num  0 0 0 0 0 0 0 0 0 0 ...\n $ own_Watch          : num  0 0 0 0 0 1 0 0 0 0 ...\n $ own_Pressure_Cooker: num  0 0 0 0 0 0 0 0 0 0 ...\n $ own_Chairs         : num  1 0 0 0 1 1 0 0 1 0 ...\n $ own_Tables         : num  0 0 0 0 0 1 0 0 0 0 ...\n $ own_Bicycle        : num  1 1 1 0 0 1 0 0 1 0 ...\n $ own_Motor_Cycle    : num  0 0 0 0 0 0 0 0 0 0 ...\n $ own_Electric_Fan   : num  0 0 0 0 0 0 0 0 0 0 ...\n $ brick_wall         : num  1 1 1 0 0 0 0 1 1 0 ...\n $ own_bov            : num  0 1 1 0 NA 1 NA NA 0 NA ...\n```\n:::\n:::\n\n\n\n2.4.4. Replacing NA\n\n\n\n::: {.cell hash='Data-Analysis-Wk2_cache/pdf/unnamed-chunk-21_1a0bf3e5058851ea897d56bff100e971'}\n\n```{.r .cell-code .numberLines}\nassets3$own_bov[is.na(assets3$own_bov)]<- 0\n#View(assets3)\ntable (assets3$own_bov, useNA = \"always\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n   0    1 <NA> \n9046 4331    0 \n```\n:::\n:::\n\n\n\n\n\n\n#### 2.5. Use PCA to create asset_index\n\nCreate the asset index using the Principle component analysis (PCA) and then categorize it in 5 quintiles of wealth.\n\n\n::: {.callout-tip}\n## What is a Principle component analysis (PCA)?\n\n*Principal Component Analysis (PCA)* is a statistical technique that is used to transform a large number of variables into a smaller number (or just 1) new variable. Is often used for making scores or index.\n\nWhen we do a score/index we tend to put equal weight to every variable because we think that every variable is equal important. But is that true? Usually no. So in *Principle component analysis* we try to put a weight to every variable depending the variance. It is useful to also put in in order to know which first component we need to work. (Which variables are representatives and in what measure)\n\nThe idea behind PCA is to find the underlying patterns in the data using its variances. The analysis will create a first (principal) component, then a second, third, and so on. Each component captures a different aspect of the variation in the data, with the first component capturing the most variation, and subsequent components capturing progressively less.\n\nUsually we use the first component and with that then create a weighted variable for each individual.\n:::\n\n\n\n::: {.cell hash='Data-Analysis-Wk2_cache/pdf/unnamed-chunk-22_7cd554b37a49f7b1ba547397ce8cd66a'}\n\n```{.r .cell-code .numberLines}\nnames(assets3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] \"FSN\"                 \"own_Radio\"           \"own_Mobile\"         \n [4] \"own_Sewing_Machine\"  \"own_Watch\"           \"own_Pressure_Cooker\"\n [7] \"own_Chairs\"          \"own_Tables\"          \"own_Bicycle\"        \n[10] \"own_Motor_Cycle\"     \"own_Electric_Fan\"    \"brick_wall\"         \n[13] \"own_bov\"            \n```\n:::\n:::\n\n\n\n2.5.1. PCA command\n\n\n\n::: {.cell hash='Data-Analysis-Wk2_cache/pdf/unnamed-chunk-23_15556fc0dd13acc89a234a246967b077'}\n\n```{.r .cell-code .numberLines}\npcamod <- princomp(~own_Radio+own_Mobile+own_Sewing_Machine++own_Watch+own_Pressure_Cooker+own_Chairs+own_Tables+own_Bicycle+own_Motor_Cycle+own_Electric_Fan+brick_wall+ own_bov, cor=TRUE, data= assets3)\n```\n:::\n\n\n\n2.5.2. Inspect the component loadings of Comp.1\n\n\n\n::: {.cell hash='Data-Analysis-Wk2_cache/pdf/unnamed-chunk-24_75f275044ffc14760f08c0bfe80bdc03'}\n\n```{.r .cell-code .numberLines}\npcamod$loadings\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nLoadings:\n                    Comp.1 Comp.2 Comp.3 Comp.4 Comp.5 Comp.6 Comp.7 Comp.8\nown_Radio            0.235  0.106  0.288  0.506  0.724         0.208       \nown_Mobile           0.321  0.245 -0.106  0.173               -0.415 -0.498\nown_Sewing_Machine   0.235 -0.274  0.302  0.125 -0.210 -0.799  0.203 -0.131\nown_Watch            0.351                0.120               -0.199  0.427\nown_Pressure_Cooker  0.310 -0.348  0.220                      -0.195  0.415\nown_Chairs           0.357  0.183 -0.334        -0.198         0.388       \nown_Tables           0.362        -0.333        -0.216  0.115  0.420       \nown_Bicycle          0.246  0.501  0.137               -0.150 -0.448       \nown_Motor_Cycle      0.296 -0.280  0.277 -0.205         0.309        -0.588\nown_Electric_Fan     0.328 -0.299        -0.228         0.286 -0.159  0.101\nbrick_wall           0.215        -0.452 -0.540  0.563 -0.357              \nown_bov                     0.523  0.485 -0.523                0.317  0.121\n                    Comp.9 Comp.10 Comp.11 Comp.12\nown_Radio                                         \nown_Mobile          -0.289  0.508  -0.162         \nown_Sewing_Machine                  0.140         \nown_Watch           -0.676 -0.420                 \nown_Pressure_Cooker  0.310  0.280  -0.573         \nown_Chairs           0.132                 -0.711 \nown_Tables           0.147                  0.696 \nown_Bicycle          0.516 -0.379   0.145         \nown_Motor_Cycle            -0.479  -0.186         \nown_Electric_Fan            0.260   0.745         \nbrick_wall                                        \nown_bov             -0.225  0.196                 \n\n               Comp.1 Comp.2 Comp.3 Comp.4 Comp.5 Comp.6 Comp.7 Comp.8 Comp.9\nSS loadings     1.000  1.000  1.000  1.000  1.000  1.000  1.000  1.000  1.000\nProportion Var  0.083  0.083  0.083  0.083  0.083  0.083  0.083  0.083  0.083\nCumulative Var  0.083  0.167  0.250  0.333  0.417  0.500  0.583  0.667  0.750\n               Comp.10 Comp.11 Comp.12\nSS loadings      1.000   1.000   1.000\nProportion Var   0.083   0.083   0.083\nCumulative Var   0.833   0.917   1.000\n```\n:::\n:::\n\n\n\n::: callout-tip\nWe have to choose one model (one component) to select their scores\n:::\n\n2.5.3. Extract the component scores\n\nCreate a variable named PC1 in assets3 from the scores un pcamod\n\n\n\n::: {.cell hash='Data-Analysis-Wk2_cache/pdf/unnamed-chunk-25_f0eb7855530180a056ca23566bb8e541'}\n\n```{.r .cell-code .numberLines}\nassets3$PC1 <- pcamod$scores[ ,1]\n#View(assets3)\n```\n:::\n\n\n\n2.5.4. Check the quintiles\n\n\n\n::: {.cell hash='Data-Analysis-Wk2_cache/pdf/unnamed-chunk-26_0d3da178746e8385a892628f2dd53f0b'}\n\n```{.r .cell-code .numberLines}\nquantile(assets3$PC1, probs = seq(0,1, 1/5))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n         0%         20%         40%         60%         80%        100% \n-2.11118368 -1.66100172 -0.98271146 -0.06987735  1.45281527  7.18120558 \n```\n:::\n:::\n\n\n\n2.5.5. Create a new categorical variable 'asset_index' with values 1-5 by quintile\n\n\n\n::: {.cell hash='Data-Analysis-Wk2_cache/pdf/unnamed-chunk-27_349014ccdac4bd037723bfcd528f5ea0'}\n\n```{.r .cell-code .numberLines}\nassets3$asset_index <- NA\nassets3$asset_index[assets3$PC1 >= -2.11118368   & assets3$PC1 <=-1.66100172  ] <- \"1\"\nassets3$asset_index[assets3$PC1 >-1.66100172    & assets3$PC1 <=-0.98271146   ] <- \"2\"\nassets3$asset_index[assets3$PC1 >-0.98271146    & assets3$PC1 <=-0.06987735    ] <- \"3\"\nassets3$asset_index[assets3$PC1 >-0.06987735     & assets3$PC1 <=1.45281527    ] <- \"4\"\nassets3$asset_index[assets3$PC1 >1.45281527     & assets3$PC1 <=7.18120558  ] <- \"5\"\n```\n:::\n\n\n\n2.5.6. Drop unnecessary variables by making a subset\n\nOr final dataset (with the Asset index) only need to have FSN and asset_index\n\n\n\n::: {.cell hash='Data-Analysis-Wk2_cache/pdf/unnamed-chunk-28_e02adc309db3ec9da9074afe0b2e860e'}\n\n```{.r .cell-code .numberLines}\nassets4 <- subset(assets3, select= c(FSN,asset_index))\nstr(assets4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t13377 obs. of  2 variables:\n $ FSN        : int  45001 45002 45003 45004 45005 45006 45007 45008 45009 45010 ...\n $ asset_index: chr  \"4\" \"3\" \"2\" \"1\" ...\n```\n:::\n\n```{.r .cell-code .numberLines}\ntable(assets4$asset_index)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n   1    2    3    4    5 \n3243 2254 2581 2632 2667 \n```\n:::\n:::\n\n\n\n\n\n### 3. Merging all the databases\n\n#### 3.1. Final Merging \n(Questionnaire_1 + asset index + animals + Q1_B + Q1_Screening)\n\n3.1.1 Opening Questionnaire_1\n\n\n\n::: {.cell hash='Data-Analysis-Wk2_cache/pdf/unnamed-chunk-29_d73043912167df756e99b6d00b5bafa0'}\n\n```{.r .cell-code .numberLines}\nQuestionnaire_1 <- read.csv(\"C:/Users/pined/OneDrive - Universidad Nacional Mayor de San Marcos/Javier 2022/Belgica/AC2_DataAnalysis_ThWk/Material/Questionnaire_1.csv\", sep=\",\", dec= \".\")\n```\n:::\n\n::: {.cell hash='Data-Analysis-Wk2_cache/pdf/unnamed-chunk-30_655db969ffef42ed4d82b776222526f7'}\n\n```{.r .cell-code .numberLines}\nstr(Questionnaire_1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t13377 obs. of  10 variables:\n $ FSN                    : int  45001 45002 45003 45004 45005 45006 45007 45008 45009 45010 ...\n $ panchyat_id            : int  2 2 2 2 2 2 2 2 2 2 ...\n $ village_id             : int  11 11 11 11 11 11 11 11 11 11 ...\n $ ward_no                : int  1 1 1 1 1 1 1 1 1 1 ...\n $ household_no           : int  21 680 290 3390 181 3501 1401 2330 3750 2371 ...\n $ household_head_age     : int  50 35 60 35 40 40 60 23 25 40 ...\n $ household_head_sex     : int  2 2 2 2 2 2 2 2 2 3 ...\n $ household_head_religion: int  4 4 4 4 4 4 4 4 4 4 ...\n $ household_head_caste   : int  9 9 9 9 9 9 9 9 9 9 ...\n $ household_head_subcaste: chr  \"PASWAN\" \"PASWAN\" \"PASWAN\" \"PASWAN\" ...\n```\n:::\n:::\n\n\n\n3.1.2 Merging with the assets\n\n\n\n::: {.cell hash='Data-Analysis-Wk2_cache/pdf/unnamed-chunk-31_492730548eeb3747ba11bce9fb0f8a86'}\n\n```{.r .cell-code .numberLines}\nQuest1_assets4  <-  merge(assets4, Questionnaire_1, all=TRUE, by = \"FSN\")\nstr(Quest1_assets4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t13377 obs. of  11 variables:\n $ FSN                    : int  45001 45002 45003 45004 45005 45006 45007 45008 45009 45010 ...\n $ asset_index            : chr  \"4\" \"3\" \"2\" \"1\" ...\n $ panchyat_id            : int  2 2 2 2 2 2 2 2 2 2 ...\n $ village_id             : int  11 11 11 11 11 11 11 11 11 11 ...\n $ ward_no                : int  1 1 1 1 1 1 1 1 1 1 ...\n $ household_no           : int  21 680 290 3390 181 3501 1401 2330 3750 2371 ...\n $ household_head_age     : int  50 35 60 35 40 40 60 23 25 40 ...\n $ household_head_sex     : int  2 2 2 2 2 2 2 2 2 3 ...\n $ household_head_religion: int  4 4 4 4 4 4 4 4 4 4 ...\n $ household_head_caste   : int  9 9 9 9 9 9 9 9 9 9 ...\n $ household_head_subcaste: chr  \"PASWAN\" \"PASWAN\" \"PASWAN\" \"PASWAN\" ...\n```\n:::\n:::\n\n\n\n3.1.3 Merging with animals\n\n\n\n::: {.cell hash='Data-Analysis-Wk2_cache/pdf/unnamed-chunk-32_ba49eec17a1ffaeb9f26490d840b2de7'}\n\n```{.r .cell-code .numberLines}\nstr(animals)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t7147 obs. of  29 variables:\n $ FSN       : int  45001 45002 45003 45004 45006 45009 45021 45024 45025 45027 ...\n $ count_Goa : num  3 0 0 2 0 7 1 3 3 0 ...\n $ dist_Goa  : int  5 NA NA 5 NA 0 5 15 0 NA ...\n $ indor_Goa : num  1 0 0 1 0 1 1 1 1 0 ...\n $ daysin_Goa: num  120 0 0 180 0 360 150 90 90 0 ...\n $ count_Pou : num  1 0 0 0 0 0 0 0 0 2 ...\n $ dist_Pou  : int  0 NA NA NA NA NA NA NA NA 0 ...\n $ indor_Pou : num  1 0 0 0 0 0 0 0 0 1 ...\n $ daysin_Pou: num  365 0 0 0 0 0 0 0 0 360 ...\n $ count_Buf : num  0 1 0 0 0 0 0 0 0 0 ...\n $ dist_Buf  : int  NA 4 NA NA NA NA NA NA NA NA ...\n $ indor_Buf : num  0 0 0 0 0 0 0 0 0 0 ...\n $ daysin_Buf: num  0 0 0 0 0 0 0 0 0 0 ...\n $ count_Cow : num  0 0 1 0 2 0 3 0 0 0 ...\n $ dist_Cow  : int  NA NA 3 NA 0 NA 15 NA NA NA ...\n $ indor_Cow : num  0 0 1 0 1 0 0 0 0 0 ...\n $ daysin_Cow: num  0 0 210 0 360 0 0 0 0 0 ...\n $ count_Pig : num  0 0 0 0 0 0 0 0 0 0 ...\n $ dist_Pig  : int  NA NA NA NA NA NA NA NA NA NA ...\n $ indor_Pig : num  0 0 0 0 0 0 0 0 0 0 ...\n $ daysin_Pig: num  0 0 0 0 0 0 0 0 0 0 ...\n $ count_Dog : num  0 0 0 0 0 0 0 0 0 0 ...\n $ dist_Dog  : int  NA NA NA NA NA NA NA NA NA NA ...\n $ indor_Dog : num  0 0 0 0 0 0 0 0 0 0 ...\n $ daysin_Dog: num  0 0 0 0 0 0 0 0 0 0 ...\n $ count_Oth : num  0 0 0 0 0 0 0 0 0 0 ...\n $ dist_Oth  : int  NA NA NA NA NA NA NA NA NA NA ...\n $ indor_Oth : num  0 0 0 0 0 0 0 0 0 0 ...\n $ daysin_Oth: num  0 0 0 0 0 0 0 0 0 0 ...\n - attr(*, \"reshapeWide\")=List of 5\n  ..$ v.names: chr [1:4] \"count\" \"dist\" \"indor\" \"daysin\"\n  ..$ timevar: chr \"anim\"\n  ..$ idvar  : chr \"FSN\"\n  ..$ times  : chr [1:7] \"Goa\" \"Pou\" \"Buf\" \"Cow\" ...\n  ..$ varying: chr [1:4, 1:7] \"count_Goa\" \"dist_Goa\" \"indor_Goa\" \"daysin_Goa\" ...\n```\n:::\n\n```{.r .cell-code .numberLines}\nstr(Quest1_assets4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t13377 obs. of  11 variables:\n $ FSN                    : int  45001 45002 45003 45004 45005 45006 45007 45008 45009 45010 ...\n $ asset_index            : chr  \"4\" \"3\" \"2\" \"1\" ...\n $ panchyat_id            : int  2 2 2 2 2 2 2 2 2 2 ...\n $ village_id             : int  11 11 11 11 11 11 11 11 11 11 ...\n $ ward_no                : int  1 1 1 1 1 1 1 1 1 1 ...\n $ household_no           : int  21 680 290 3390 181 3501 1401 2330 3750 2371 ...\n $ household_head_age     : int  50 35 60 35 40 40 60 23 25 40 ...\n $ household_head_sex     : int  2 2 2 2 2 2 2 2 2 3 ...\n $ household_head_religion: int  4 4 4 4 4 4 4 4 4 4 ...\n $ household_head_caste   : int  9 9 9 9 9 9 9 9 9 9 ...\n $ household_head_subcaste: chr  \"PASWAN\" \"PASWAN\" \"PASWAN\" \"PASWAN\" ...\n```\n:::\n\n```{.r .cell-code .numberLines}\nQuest1_assets4_animals <-  merge(Quest1_assets4, animals, all=TRUE, by = \"FSN\")\nstr(Quest1_assets4_animals)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t13377 obs. of  39 variables:\n $ FSN                    : int  45001 45002 45003 45004 45005 45006 45007 45008 45009 45010 ...\n $ asset_index            : chr  \"4\" \"3\" \"2\" \"1\" ...\n $ panchyat_id            : int  2 2 2 2 2 2 2 2 2 2 ...\n $ village_id             : int  11 11 11 11 11 11 11 11 11 11 ...\n $ ward_no                : int  1 1 1 1 1 1 1 1 1 1 ...\n $ household_no           : int  21 680 290 3390 181 3501 1401 2330 3750 2371 ...\n $ household_head_age     : int  50 35 60 35 40 40 60 23 25 40 ...\n $ household_head_sex     : int  2 2 2 2 2 2 2 2 2 3 ...\n $ household_head_religion: int  4 4 4 4 4 4 4 4 4 4 ...\n $ household_head_caste   : int  9 9 9 9 9 9 9 9 9 9 ...\n $ household_head_subcaste: chr  \"PASWAN\" \"PASWAN\" \"PASWAN\" \"PASWAN\" ...\n $ count_Goa              : num  3 0 0 2 NA 0 NA NA 7 NA ...\n $ dist_Goa               : int  5 NA NA 5 NA NA NA NA 0 NA ...\n $ indor_Goa              : num  1 0 0 1 NA 0 NA NA 1 NA ...\n $ daysin_Goa             : num  120 0 0 180 NA 0 NA NA 360 NA ...\n $ count_Pou              : num  1 0 0 0 NA 0 NA NA 0 NA ...\n $ dist_Pou               : int  0 NA NA NA NA NA NA NA NA NA ...\n $ indor_Pou              : num  1 0 0 0 NA 0 NA NA 0 NA ...\n $ daysin_Pou             : num  365 0 0 0 NA 0 NA NA 0 NA ...\n $ count_Buf              : num  0 1 0 0 NA 0 NA NA 0 NA ...\n $ dist_Buf               : int  NA 4 NA NA NA NA NA NA NA NA ...\n $ indor_Buf              : num  0 0 0 0 NA 0 NA NA 0 NA ...\n $ daysin_Buf             : num  0 0 0 0 NA 0 NA NA 0 NA ...\n $ count_Cow              : num  0 0 1 0 NA 2 NA NA 0 NA ...\n $ dist_Cow               : int  NA NA 3 NA NA 0 NA NA NA NA ...\n $ indor_Cow              : num  0 0 1 0 NA 1 NA NA 0 NA ...\n $ daysin_Cow             : num  0 0 210 0 NA 360 NA NA 0 NA ...\n $ count_Pig              : num  0 0 0 0 NA 0 NA NA 0 NA ...\n $ dist_Pig               : int  NA NA NA NA NA NA NA NA NA NA ...\n $ indor_Pig              : num  0 0 0 0 NA 0 NA NA 0 NA ...\n $ daysin_Pig             : num  0 0 0 0 NA 0 NA NA 0 NA ...\n $ count_Dog              : num  0 0 0 0 NA 0 NA NA 0 NA ...\n $ dist_Dog               : int  NA NA NA NA NA NA NA NA NA NA ...\n $ indor_Dog              : num  0 0 0 0 NA 0 NA NA 0 NA ...\n $ daysin_Dog             : num  0 0 0 0 NA 0 NA NA 0 NA ...\n $ count_Oth              : num  0 0 0 0 NA 0 NA NA 0 NA ...\n $ dist_Oth               : int  NA NA NA NA NA NA NA NA NA NA ...\n $ indor_Oth              : num  0 0 0 0 NA 0 NA NA 0 NA ...\n $ daysin_Oth             : num  0 0 0 0 NA 0 NA NA 0 NA ...\n```\n:::\n\n```{.r .cell-code .numberLines}\n#View(Quest1_assets4_animals)\n```\n:::\n\n\n\n3.1.4 Merging with Q1_B\n\n\n\n::: {.cell hash='Data-Analysis-Wk2_cache/pdf/unnamed-chunk-33_79accf88da8fca4394ca88ff27819c89'}\n\n```{.r .cell-code .numberLines}\nQ1_B <- read.csv(\"C:/Users/pined/OneDrive - Universidad Nacional Mayor de San Marcos/Javier 2022/Belgica/AC2_DataAnalysis_ThWk/Material/Q1_B.csv\", sep=\",\", dec= \".\")\nstr(Q1_B)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t13377 obs. of  40 variables:\n $ ID                 : int  1 2 3 4 5 6 7 8 9 10 ...\n $ FSN                : num  45001 45002 45003 45004 45005 ...\n $ Neem_Tree          : num  0 0 0 0 0 0 0 0 0 0 ...\n $ Neem_Tree_Distance : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Neem_Tree_Size     : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Neem_Tree_Age      : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Neem_Tree_Usage    : chr  \"\" \"\" \"\" \"\" ...\n $ Neem_Tree_Use_Other: chr  \"\" \"\" \"\" \"\" ...\n $ Bamboo_Tree        : num  1 1 1 1 1 1 1 1 1 1 ...\n $ Bamboo_Tree_Dist   : num  3 10 16 17 5 4 15 3 1 10 ...\n $ Banana_Tree        : num  0 0 0 0 0 0 0 1 1 0 ...\n $ Banana_Tree_Dist   : num  -1 -1 -1 -1 -1 -1 -1 5 1 -1 ...\n $ Rice_Field         : num  1 1 1 1 1 1 1 1 1 1 ...\n $ Rice_Field_Dist    : num  4 12 16 13 4 13 10 10 7 12 ...\n $ Perm_Water_Body    : num  0 0 0 0 0 0 0 0 0 0 ...\n $ Perm_Wat_Body_Dist : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Wat_Body_Mid_Point : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ No_Mosquito_Net    : num  0 2 1 0 0 0 0 0 1 0 ...\n $ Sprayed_2010       : num  86 86 86 86 86 86 86 86 86 86 ...\n $ Sprayed_2009       : num  86 86 86 86 86 86 86 86 86 86 ...\n $ Floor_Material     : num  153 153 153 153 153 153 153 153 155 153 ...\n $ Other_Floor_Mat    : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Is_Floor_Damp      : num  1 1 1 1 1 1 1 1 0 1 ...\n $ Roof_Material      : num  161 159 158 156 156 156 156 158 158 156 ...\n $ Other_Roof_Material: num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Wall_Material      : num  164 164 164 162 163 163 162 164 164 162 ...\n $ Other_Wall_Material: num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Windows_in_Room    : num  1 1 1 0 0 0 0 1 1 0 ...\n $ Granaries_in_HH    : num  1 1 1 0 1 1 0 1 1 0 ...\n $ Source_Drink_Water : num  167 167 92 92 92 92 92 92 92 92 ...\n $ Other_Src_Drink_Wat: num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Toilet_Facility    : num  177 177 177 177 177 177 177 177 177 177 ...\n $ Other_Toilet_Fac   : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Cooking_Fuel       : num  180 180 180 180 180 180 180 180 180 180 ...\n $ Other_Cooking_Fuel : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Source_Light       : num  182 182 182 182 182 182 182 182 182 182 ...\n $ Other_Source_Light : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Electricity_in_HH  : num  0 0 0 0 0 0 0 0 0 0 ...\n $ No_Of_Rooms        : num  2 2 3 1 2 3 2 1 3 1 ...\n $ No_Sleeping_Rooms  : num  2 2 2 1 2 2 2 1 1 1 ...\n```\n:::\n\n```{.r .cell-code .numberLines}\n#Merge\nQuest1_assets4_animals_q1B <-  merge(Q1_B, Quest1_assets4_animals, all=TRUE, by = \"FSN\")\nstr(Quest1_assets4_animals_q1B)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t13377 obs. of  78 variables:\n $ FSN                    : num  45001 45002 45003 45004 45005 ...\n $ ID                     : int  1 2 3 4 5 6 7 8 9 10 ...\n $ Neem_Tree              : num  0 0 0 0 0 0 0 0 0 0 ...\n $ Neem_Tree_Distance     : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Neem_Tree_Size         : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Neem_Tree_Age          : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Neem_Tree_Usage        : chr  \"\" \"\" \"\" \"\" ...\n $ Neem_Tree_Use_Other    : chr  \"\" \"\" \"\" \"\" ...\n $ Bamboo_Tree            : num  1 1 1 1 1 1 1 1 1 1 ...\n $ Bamboo_Tree_Dist       : num  3 10 16 17 5 4 15 3 1 10 ...\n $ Banana_Tree            : num  0 0 0 0 0 0 0 1 1 0 ...\n $ Banana_Tree_Dist       : num  -1 -1 -1 -1 -1 -1 -1 5 1 -1 ...\n $ Rice_Field             : num  1 1 1 1 1 1 1 1 1 1 ...\n $ Rice_Field_Dist        : num  4 12 16 13 4 13 10 10 7 12 ...\n $ Perm_Water_Body        : num  0 0 0 0 0 0 0 0 0 0 ...\n $ Perm_Wat_Body_Dist     : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Wat_Body_Mid_Point     : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ No_Mosquito_Net        : num  0 2 1 0 0 0 0 0 1 0 ...\n $ Sprayed_2010           : num  86 86 86 86 86 86 86 86 86 86 ...\n $ Sprayed_2009           : num  86 86 86 86 86 86 86 86 86 86 ...\n $ Floor_Material         : num  153 153 153 153 153 153 153 153 155 153 ...\n $ Other_Floor_Mat        : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Is_Floor_Damp          : num  1 1 1 1 1 1 1 1 0 1 ...\n $ Roof_Material          : num  161 159 158 156 156 156 156 158 158 156 ...\n $ Other_Roof_Material    : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Wall_Material          : num  164 164 164 162 163 163 162 164 164 162 ...\n $ Other_Wall_Material    : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Windows_in_Room        : num  1 1 1 0 0 0 0 1 1 0 ...\n $ Granaries_in_HH        : num  1 1 1 0 1 1 0 1 1 0 ...\n $ Source_Drink_Water     : num  167 167 92 92 92 92 92 92 92 92 ...\n $ Other_Src_Drink_Wat    : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Toilet_Facility        : num  177 177 177 177 177 177 177 177 177 177 ...\n $ Other_Toilet_Fac       : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Cooking_Fuel           : num  180 180 180 180 180 180 180 180 180 180 ...\n $ Other_Cooking_Fuel     : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Source_Light           : num  182 182 182 182 182 182 182 182 182 182 ...\n $ Other_Source_Light     : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Electricity_in_HH      : num  0 0 0 0 0 0 0 0 0 0 ...\n $ No_Of_Rooms            : num  2 2 3 1 2 3 2 1 3 1 ...\n $ No_Sleeping_Rooms      : num  2 2 2 1 2 2 2 1 1 1 ...\n $ asset_index            : chr  \"4\" \"3\" \"2\" \"1\" ...\n $ panchyat_id            : int  2 2 2 2 2 2 2 2 2 2 ...\n $ village_id             : int  11 11 11 11 11 11 11 11 11 11 ...\n $ ward_no                : int  1 1 1 1 1 1 1 1 1 1 ...\n $ household_no           : int  21 680 290 3390 181 3501 1401 2330 3750 2371 ...\n $ household_head_age     : int  50 35 60 35 40 40 60 23 25 40 ...\n $ household_head_sex     : int  2 2 2 2 2 2 2 2 2 3 ...\n $ household_head_religion: int  4 4 4 4 4 4 4 4 4 4 ...\n $ household_head_caste   : int  9 9 9 9 9 9 9 9 9 9 ...\n $ household_head_subcaste: chr  \"PASWAN\" \"PASWAN\" \"PASWAN\" \"PASWAN\" ...\n $ count_Goa              : num  3 0 0 2 NA 0 NA NA 7 NA ...\n $ dist_Goa               : int  5 NA NA 5 NA NA NA NA 0 NA ...\n $ indor_Goa              : num  1 0 0 1 NA 0 NA NA 1 NA ...\n $ daysin_Goa             : num  120 0 0 180 NA 0 NA NA 360 NA ...\n $ count_Pou              : num  1 0 0 0 NA 0 NA NA 0 NA ...\n $ dist_Pou               : int  0 NA NA NA NA NA NA NA NA NA ...\n $ indor_Pou              : num  1 0 0 0 NA 0 NA NA 0 NA ...\n $ daysin_Pou             : num  365 0 0 0 NA 0 NA NA 0 NA ...\n $ count_Buf              : num  0 1 0 0 NA 0 NA NA 0 NA ...\n $ dist_Buf               : int  NA 4 NA NA NA NA NA NA NA NA ...\n $ indor_Buf              : num  0 0 0 0 NA 0 NA NA 0 NA ...\n $ daysin_Buf             : num  0 0 0 0 NA 0 NA NA 0 NA ...\n $ count_Cow              : num  0 0 1 0 NA 2 NA NA 0 NA ...\n $ dist_Cow               : int  NA NA 3 NA NA 0 NA NA NA NA ...\n $ indor_Cow              : num  0 0 1 0 NA 1 NA NA 0 NA ...\n $ daysin_Cow             : num  0 0 210 0 NA 360 NA NA 0 NA ...\n $ count_Pig              : num  0 0 0 0 NA 0 NA NA 0 NA ...\n $ dist_Pig               : int  NA NA NA NA NA NA NA NA NA NA ...\n $ indor_Pig              : num  0 0 0 0 NA 0 NA NA 0 NA ...\n $ daysin_Pig             : num  0 0 0 0 NA 0 NA NA 0 NA ...\n $ count_Dog              : num  0 0 0 0 NA 0 NA NA 0 NA ...\n $ dist_Dog               : int  NA NA NA NA NA NA NA NA NA NA ...\n $ indor_Dog              : num  0 0 0 0 NA 0 NA NA 0 NA ...\n $ daysin_Dog             : num  0 0 0 0 NA 0 NA NA 0 NA ...\n $ count_Oth              : num  0 0 0 0 NA 0 NA NA 0 NA ...\n $ dist_Oth               : int  NA NA NA NA NA NA NA NA NA NA ...\n $ indor_Oth              : num  0 0 0 0 NA 0 NA NA 0 NA ...\n $ daysin_Oth             : num  0 0 0 0 NA 0 NA NA 0 NA ...\n```\n:::\n:::\n\n\n\n3.1.5 Opening Q1_Screening.csv\n\n\n\n::: {.cell hash='Data-Analysis-Wk2_cache/pdf/unnamed-chunk-34_29259f14e22506b6b26345bec4473680'}\n\n```{.r .cell-code .numberLines}\nQ1_Screening <- read.csv(\"C:/Users/pined/OneDrive - Universidad Nacional Mayor de San Marcos/Javier 2022/Belgica/AC2_DataAnalysis_ThWk/Material/Q1_Screening.csv\", sep=\",\", dec= \".\")\nstr(Q1_Screening)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t81214 obs. of  10 variables:\n $ FSN                         : int  45001 45001 45001 45001 45001 45001 45002 45002 45002 45002 ...\n $ member_id                   : int  1 2 3 4 5 6 1 2 3 4 ...\n $ member_age                  : int  50 48 25 22 0 11 35 33 17 15 ...\n $ member_sex                  : int  2 3 2 3 2 2 2 3 2 2 ...\n $ fever_gt_3_days             : int  0 0 0 0 0 0 0 0 0 0 ...\n $ suffered_vl_since_2nd_survey: int  0 0 0 0 0 0 0 0 0 0 ...\n $ date_diagnosis              : chr  \"\" \"\" \"\" \"\" ...\n $ treatment_place             : chr  \"-1\" \"-1\" \"-1\" \"-1\" ...\n $ current_status              : int  0 0 4 0 0 0 0 0 4 0 ...\n $ datedis                     : int  NA NA NA NA NA NA NA NA NA NA ...\n```\n:::\n:::\n\n\n\n3.1.6 Merging with the merged database of households\n\n\n\n::: {.cell hash='Data-Analysis-Wk2_cache/pdf/unnamed-chunk-35_50e333d95d5813cd9d760435d6a4b784'}\n\n```{.r .cell-code .numberLines}\nstr(Quest1_assets4_animals_q1B)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t13377 obs. of  78 variables:\n $ FSN                    : num  45001 45002 45003 45004 45005 ...\n $ ID                     : int  1 2 3 4 5 6 7 8 9 10 ...\n $ Neem_Tree              : num  0 0 0 0 0 0 0 0 0 0 ...\n $ Neem_Tree_Distance     : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Neem_Tree_Size         : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Neem_Tree_Age          : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Neem_Tree_Usage        : chr  \"\" \"\" \"\" \"\" ...\n $ Neem_Tree_Use_Other    : chr  \"\" \"\" \"\" \"\" ...\n $ Bamboo_Tree            : num  1 1 1 1 1 1 1 1 1 1 ...\n $ Bamboo_Tree_Dist       : num  3 10 16 17 5 4 15 3 1 10 ...\n $ Banana_Tree            : num  0 0 0 0 0 0 0 1 1 0 ...\n $ Banana_Tree_Dist       : num  -1 -1 -1 -1 -1 -1 -1 5 1 -1 ...\n $ Rice_Field             : num  1 1 1 1 1 1 1 1 1 1 ...\n $ Rice_Field_Dist        : num  4 12 16 13 4 13 10 10 7 12 ...\n $ Perm_Water_Body        : num  0 0 0 0 0 0 0 0 0 0 ...\n $ Perm_Wat_Body_Dist     : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Wat_Body_Mid_Point     : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ No_Mosquito_Net        : num  0 2 1 0 0 0 0 0 1 0 ...\n $ Sprayed_2010           : num  86 86 86 86 86 86 86 86 86 86 ...\n $ Sprayed_2009           : num  86 86 86 86 86 86 86 86 86 86 ...\n $ Floor_Material         : num  153 153 153 153 153 153 153 153 155 153 ...\n $ Other_Floor_Mat        : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Is_Floor_Damp          : num  1 1 1 1 1 1 1 1 0 1 ...\n $ Roof_Material          : num  161 159 158 156 156 156 156 158 158 156 ...\n $ Other_Roof_Material    : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Wall_Material          : num  164 164 164 162 163 163 162 164 164 162 ...\n $ Other_Wall_Material    : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Windows_in_Room        : num  1 1 1 0 0 0 0 1 1 0 ...\n $ Granaries_in_HH        : num  1 1 1 0 1 1 0 1 1 0 ...\n $ Source_Drink_Water     : num  167 167 92 92 92 92 92 92 92 92 ...\n $ Other_Src_Drink_Wat    : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Toilet_Facility        : num  177 177 177 177 177 177 177 177 177 177 ...\n $ Other_Toilet_Fac       : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Cooking_Fuel           : num  180 180 180 180 180 180 180 180 180 180 ...\n $ Other_Cooking_Fuel     : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Source_Light           : num  182 182 182 182 182 182 182 182 182 182 ...\n $ Other_Source_Light     : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Electricity_in_HH      : num  0 0 0 0 0 0 0 0 0 0 ...\n $ No_Of_Rooms            : num  2 2 3 1 2 3 2 1 3 1 ...\n $ No_Sleeping_Rooms      : num  2 2 2 1 2 2 2 1 1 1 ...\n $ asset_index            : chr  \"4\" \"3\" \"2\" \"1\" ...\n $ panchyat_id            : int  2 2 2 2 2 2 2 2 2 2 ...\n $ village_id             : int  11 11 11 11 11 11 11 11 11 11 ...\n $ ward_no                : int  1 1 1 1 1 1 1 1 1 1 ...\n $ household_no           : int  21 680 290 3390 181 3501 1401 2330 3750 2371 ...\n $ household_head_age     : int  50 35 60 35 40 40 60 23 25 40 ...\n $ household_head_sex     : int  2 2 2 2 2 2 2 2 2 3 ...\n $ household_head_religion: int  4 4 4 4 4 4 4 4 4 4 ...\n $ household_head_caste   : int  9 9 9 9 9 9 9 9 9 9 ...\n $ household_head_subcaste: chr  \"PASWAN\" \"PASWAN\" \"PASWAN\" \"PASWAN\" ...\n $ count_Goa              : num  3 0 0 2 NA 0 NA NA 7 NA ...\n $ dist_Goa               : int  5 NA NA 5 NA NA NA NA 0 NA ...\n $ indor_Goa              : num  1 0 0 1 NA 0 NA NA 1 NA ...\n $ daysin_Goa             : num  120 0 0 180 NA 0 NA NA 360 NA ...\n $ count_Pou              : num  1 0 0 0 NA 0 NA NA 0 NA ...\n $ dist_Pou               : int  0 NA NA NA NA NA NA NA NA NA ...\n $ indor_Pou              : num  1 0 0 0 NA 0 NA NA 0 NA ...\n $ daysin_Pou             : num  365 0 0 0 NA 0 NA NA 0 NA ...\n $ count_Buf              : num  0 1 0 0 NA 0 NA NA 0 NA ...\n $ dist_Buf               : int  NA 4 NA NA NA NA NA NA NA NA ...\n $ indor_Buf              : num  0 0 0 0 NA 0 NA NA 0 NA ...\n $ daysin_Buf             : num  0 0 0 0 NA 0 NA NA 0 NA ...\n $ count_Cow              : num  0 0 1 0 NA 2 NA NA 0 NA ...\n $ dist_Cow               : int  NA NA 3 NA NA 0 NA NA NA NA ...\n $ indor_Cow              : num  0 0 1 0 NA 1 NA NA 0 NA ...\n $ daysin_Cow             : num  0 0 210 0 NA 360 NA NA 0 NA ...\n $ count_Pig              : num  0 0 0 0 NA 0 NA NA 0 NA ...\n $ dist_Pig               : int  NA NA NA NA NA NA NA NA NA NA ...\n $ indor_Pig              : num  0 0 0 0 NA 0 NA NA 0 NA ...\n $ daysin_Pig             : num  0 0 0 0 NA 0 NA NA 0 NA ...\n $ count_Dog              : num  0 0 0 0 NA 0 NA NA 0 NA ...\n $ dist_Dog               : int  NA NA NA NA NA NA NA NA NA NA ...\n $ indor_Dog              : num  0 0 0 0 NA 0 NA NA 0 NA ...\n $ daysin_Dog             : num  0 0 0 0 NA 0 NA NA 0 NA ...\n $ count_Oth              : num  0 0 0 0 NA 0 NA NA 0 NA ...\n $ dist_Oth               : int  NA NA NA NA NA NA NA NA NA NA ...\n $ indor_Oth              : num  0 0 0 0 NA 0 NA NA 0 NA ...\n $ daysin_Oth             : num  0 0 0 0 NA 0 NA NA 0 NA ...\n```\n:::\n\n```{.r .cell-code .numberLines}\nstr(Q1_Screening)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t81214 obs. of  10 variables:\n $ FSN                         : int  45001 45001 45001 45001 45001 45001 45002 45002 45002 45002 ...\n $ member_id                   : int  1 2 3 4 5 6 1 2 3 4 ...\n $ member_age                  : int  50 48 25 22 0 11 35 33 17 15 ...\n $ member_sex                  : int  2 3 2 3 2 2 2 3 2 2 ...\n $ fever_gt_3_days             : int  0 0 0 0 0 0 0 0 0 0 ...\n $ suffered_vl_since_2nd_survey: int  0 0 0 0 0 0 0 0 0 0 ...\n $ date_diagnosis              : chr  \"\" \"\" \"\" \"\" ...\n $ treatment_place             : chr  \"-1\" \"-1\" \"-1\" \"-1\" ...\n $ current_status              : int  0 0 4 0 0 0 0 0 4 0 ...\n $ datedis                     : int  NA NA NA NA NA NA NA NA NA NA ...\n```\n:::\n\n```{.r .cell-code .numberLines}\n#Merge\nQuest1_assets4_animals_q1B_Persons <-  merge(Q1_Screening, Quest1_assets4_animals_q1B, all=TRUE, by = \"FSN\")\nstr(Quest1_assets4_animals_q1B_Persons)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t81214 obs. of  87 variables:\n $ FSN                         : int  45001 45001 45001 45001 45001 45001 45002 45002 45002 45002 ...\n $ member_id                   : int  1 2 3 4 5 6 1 2 3 4 ...\n $ member_age                  : int  50 48 25 22 0 11 35 33 17 15 ...\n $ member_sex                  : int  2 3 2 3 2 2 2 3 2 2 ...\n $ fever_gt_3_days             : int  0 0 0 0 0 0 0 0 0 0 ...\n $ suffered_vl_since_2nd_survey: int  0 0 0 0 0 0 0 0 0 0 ...\n $ date_diagnosis              : chr  \"\" \"\" \"\" \"\" ...\n $ treatment_place             : chr  \"-1\" \"-1\" \"-1\" \"-1\" ...\n $ current_status              : int  0 0 4 0 0 0 0 0 4 0 ...\n $ datedis                     : int  NA NA NA NA NA NA NA NA NA NA ...\n $ ID                          : int  1 1 1 1 1 1 2 2 2 2 ...\n $ Neem_Tree                   : num  0 0 0 0 0 0 0 0 0 0 ...\n $ Neem_Tree_Distance          : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Neem_Tree_Size              : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Neem_Tree_Age               : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Neem_Tree_Usage             : chr  \"\" \"\" \"\" \"\" ...\n $ Neem_Tree_Use_Other         : chr  \"\" \"\" \"\" \"\" ...\n $ Bamboo_Tree                 : num  1 1 1 1 1 1 1 1 1 1 ...\n $ Bamboo_Tree_Dist            : num  3 3 3 3 3 3 10 10 10 10 ...\n $ Banana_Tree                 : num  0 0 0 0 0 0 0 0 0 0 ...\n $ Banana_Tree_Dist            : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Rice_Field                  : num  1 1 1 1 1 1 1 1 1 1 ...\n $ Rice_Field_Dist             : num  4 4 4 4 4 4 12 12 12 12 ...\n $ Perm_Water_Body             : num  0 0 0 0 0 0 0 0 0 0 ...\n $ Perm_Wat_Body_Dist          : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Wat_Body_Mid_Point          : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ No_Mosquito_Net             : num  0 0 0 0 0 0 2 2 2 2 ...\n $ Sprayed_2010                : num  86 86 86 86 86 86 86 86 86 86 ...\n $ Sprayed_2009                : num  86 86 86 86 86 86 86 86 86 86 ...\n $ Floor_Material              : num  153 153 153 153 153 153 153 153 153 153 ...\n $ Other_Floor_Mat             : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Is_Floor_Damp               : num  1 1 1 1 1 1 1 1 1 1 ...\n $ Roof_Material               : num  161 161 161 161 161 161 159 159 159 159 ...\n $ Other_Roof_Material         : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Wall_Material               : num  164 164 164 164 164 164 164 164 164 164 ...\n $ Other_Wall_Material         : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Windows_in_Room             : num  1 1 1 1 1 1 1 1 1 1 ...\n $ Granaries_in_HH             : num  1 1 1 1 1 1 1 1 1 1 ...\n $ Source_Drink_Water          : num  167 167 167 167 167 167 167 167 167 167 ...\n $ Other_Src_Drink_Wat         : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Toilet_Facility             : num  177 177 177 177 177 177 177 177 177 177 ...\n $ Other_Toilet_Fac            : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Cooking_Fuel                : num  180 180 180 180 180 180 180 180 180 180 ...\n $ Other_Cooking_Fuel          : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Source_Light                : num  182 182 182 182 182 182 182 182 182 182 ...\n $ Other_Source_Light          : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Electricity_in_HH           : num  0 0 0 0 0 0 0 0 0 0 ...\n $ No_Of_Rooms                 : num  2 2 2 2 2 2 2 2 2 2 ...\n $ No_Sleeping_Rooms           : num  2 2 2 2 2 2 2 2 2 2 ...\n $ asset_index                 : chr  \"4\" \"4\" \"4\" \"4\" ...\n $ panchyat_id                 : int  2 2 2 2 2 2 2 2 2 2 ...\n $ village_id                  : int  11 11 11 11 11 11 11 11 11 11 ...\n $ ward_no                     : int  1 1 1 1 1 1 1 1 1 1 ...\n $ household_no                : int  21 21 21 21 21 21 680 680 680 680 ...\n $ household_head_age          : int  50 50 50 50 50 50 35 35 35 35 ...\n $ household_head_sex          : int  2 2 2 2 2 2 2 2 2 2 ...\n $ household_head_religion     : int  4 4 4 4 4 4 4 4 4 4 ...\n $ household_head_caste        : int  9 9 9 9 9 9 9 9 9 9 ...\n $ household_head_subcaste     : chr  \"PASWAN\" \"PASWAN\" \"PASWAN\" \"PASWAN\" ...\n $ count_Goa                   : num  3 3 3 3 3 3 0 0 0 0 ...\n $ dist_Goa                    : int  5 5 5 5 5 5 NA NA NA NA ...\n $ indor_Goa                   : num  1 1 1 1 1 1 0 0 0 0 ...\n $ daysin_Goa                  : num  120 120 120 120 120 120 0 0 0 0 ...\n $ count_Pou                   : num  1 1 1 1 1 1 0 0 0 0 ...\n $ dist_Pou                    : int  0 0 0 0 0 0 NA NA NA NA ...\n $ indor_Pou                   : num  1 1 1 1 1 1 0 0 0 0 ...\n $ daysin_Pou                  : num  365 365 365 365 365 365 0 0 0 0 ...\n $ count_Buf                   : num  0 0 0 0 0 0 1 1 1 1 ...\n $ dist_Buf                    : int  NA NA NA NA NA NA 4 4 4 4 ...\n $ indor_Buf                   : num  0 0 0 0 0 0 0 0 0 0 ...\n $ daysin_Buf                  : num  0 0 0 0 0 0 0 0 0 0 ...\n $ count_Cow                   : num  0 0 0 0 0 0 0 0 0 0 ...\n $ dist_Cow                    : int  NA NA NA NA NA NA NA NA NA NA ...\n $ indor_Cow                   : num  0 0 0 0 0 0 0 0 0 0 ...\n $ daysin_Cow                  : num  0 0 0 0 0 0 0 0 0 0 ...\n $ count_Pig                   : num  0 0 0 0 0 0 0 0 0 0 ...\n $ dist_Pig                    : int  NA NA NA NA NA NA NA NA NA NA ...\n $ indor_Pig                   : num  0 0 0 0 0 0 0 0 0 0 ...\n $ daysin_Pig                  : num  0 0 0 0 0 0 0 0 0 0 ...\n $ count_Dog                   : num  0 0 0 0 0 0 0 0 0 0 ...\n $ dist_Dog                    : int  NA NA NA NA NA NA NA NA NA NA ...\n $ indor_Dog                   : num  0 0 0 0 0 0 0 0 0 0 ...\n $ daysin_Dog                  : num  0 0 0 0 0 0 0 0 0 0 ...\n $ count_Oth                   : num  0 0 0 0 0 0 0 0 0 0 ...\n $ dist_Oth                    : int  NA NA NA NA NA NA NA NA NA NA ...\n $ indor_Oth                   : num  0 0 0 0 0 0 0 0 0 0 ...\n $ daysin_Oth                  : num  0 0 0 0 0 0 0 0 0 0 ...\n```\n:::\n:::\n\n\n\n\n#### 3.2. Select variables of interest\nFor the final dataset\n\n\n\n::: {.cell hash='Data-Analysis-Wk2_cache/pdf/unnamed-chunk-36_ebed12b37c19f509664bed40f10873d8'}\n\n```{.r .cell-code .numberLines}\nfinal_dataset  <- subset(Quest1_assets4_animals_q1B_Persons, select=c(\n  FSN, asset_index, Bamboo_Tree, Banana_Tree, Cooking_Fuel, Floor_Material, Granaries_in_HH, household_head_subcaste, indor_Buf, indor_Cow, indor_Pou, indor_Goa, count_Cow, count_Buf, count_Goa, count_Pou, Is_Floor_Damp, member_age, member_sex, Neem_Tree, No_Mosquito_Net, Perm_Water_Body, Rice_Field, Roof_Material, Sprayed_2009, Sprayed_2010, suffered_vl_since_2nd_survey, Wall_Material, Windows_in_Room\n))\n\nstr(final_dataset)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t81214 obs. of  29 variables:\n $ FSN                         : int  45001 45001 45001 45001 45001 45001 45002 45002 45002 45002 ...\n $ asset_index                 : chr  \"4\" \"4\" \"4\" \"4\" ...\n $ Bamboo_Tree                 : num  1 1 1 1 1 1 1 1 1 1 ...\n $ Banana_Tree                 : num  0 0 0 0 0 0 0 0 0 0 ...\n $ Cooking_Fuel                : num  180 180 180 180 180 180 180 180 180 180 ...\n $ Floor_Material              : num  153 153 153 153 153 153 153 153 153 153 ...\n $ Granaries_in_HH             : num  1 1 1 1 1 1 1 1 1 1 ...\n $ household_head_subcaste     : chr  \"PASWAN\" \"PASWAN\" \"PASWAN\" \"PASWAN\" ...\n $ indor_Buf                   : num  0 0 0 0 0 0 0 0 0 0 ...\n $ indor_Cow                   : num  0 0 0 0 0 0 0 0 0 0 ...\n $ indor_Pou                   : num  1 1 1 1 1 1 0 0 0 0 ...\n $ indor_Goa                   : num  1 1 1 1 1 1 0 0 0 0 ...\n $ count_Cow                   : num  0 0 0 0 0 0 0 0 0 0 ...\n $ count_Buf                   : num  0 0 0 0 0 0 1 1 1 1 ...\n $ count_Goa                   : num  3 3 3 3 3 3 0 0 0 0 ...\n $ count_Pou                   : num  1 1 1 1 1 1 0 0 0 0 ...\n $ Is_Floor_Damp               : num  1 1 1 1 1 1 1 1 1 1 ...\n $ member_age                  : int  50 48 25 22 0 11 35 33 17 15 ...\n $ member_sex                  : int  2 3 2 3 2 2 2 3 2 2 ...\n $ Neem_Tree                   : num  0 0 0 0 0 0 0 0 0 0 ...\n $ No_Mosquito_Net             : num  0 0 0 0 0 0 2 2 2 2 ...\n $ Perm_Water_Body             : num  0 0 0 0 0 0 0 0 0 0 ...\n $ Rice_Field                  : num  1 1 1 1 1 1 1 1 1 1 ...\n $ Roof_Material               : num  161 161 161 161 161 161 159 159 159 159 ...\n $ Sprayed_2009                : num  86 86 86 86 86 86 86 86 86 86 ...\n $ Sprayed_2010                : num  86 86 86 86 86 86 86 86 86 86 ...\n $ suffered_vl_since_2nd_survey: int  0 0 0 0 0 0 0 0 0 0 ...\n $ Wall_Material               : num  164 164 164 164 164 164 164 164 164 164 ...\n $ Windows_in_Room             : num  1 1 1 1 1 1 1 1 1 1 ...\n```\n:::\n:::\n\n\n\nWe are going to save this final data set\n\n\n\n::: {.cell hash='Data-Analysis-Wk2_cache/pdf/unnamed-chunk-37_43249e382e4d646a6a909fc4cdecc731'}\n\n```{.r .cell-code .numberLines}\nsaveRDS(final_dataset, \"final_dataset.RDS\")\n```\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}